/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, SBWallpaperEffectView;

__attribute__((visibility("hidden")))
@interface _SBDockBackgroundView : XXUnknownSuperclass {
	UIImage* _maskImage;
	float _maskHeight;
	SBWallpaperEffectView* _maskedView;
	SBWallpaperEffectView* _unmaskedView;
}
-(void)setStyle:(int)style;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithMaskImage:(id)maskImage;
@end

