/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_SBIconProgressStateTransition.h"


__attribute__((visibility("hidden")))
@interface _SBIconProgressLoadingNoneStateTransition : _SBIconProgressStateTransition {
}
-(void)_updateView:(id)view;
@end

