/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class _SBFolderPageElement;

__attribute__((visibility("hidden")))
@interface _SBIconGridWrapperView : XXUnknownSuperclass {
	_SBFolderPageElement* _element;
}
@property(retain, nonatomic) _SBFolderPageElement* element;
-(void)dealloc;
-(void)positionAtRow:(unsigned)row;
-(void)reposition;
@end

