/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWidgetViewControllerHost.h"
#import "_SBUIWidgetHost.h"

@class _SBUIWidgetViewController;

__attribute__((visibility("hidden")))
@interface _SBWidgetViewControllerHostInProcess : SBWidgetViewControllerHost <_SBUIWidgetHost> {
	_SBUIWidgetViewController* _widgetViewController;
}
-(void)hostDidDismiss;
-(void)hostWillDismiss;
-(void)hostDidPresent;
-(void)hostWillPresent;
-(void)invalidatePreferredViewSize;
-(void)requestLaunchOfURL:(id)url;
-(void)requestPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context completion:(id)completion;
-(void)viewDidLoad;
-(void)requestPreferredViewSizeWithHandler:(id)handler;
-(void)dealloc;
-(id)initWithWidgetIdentifier:(id)widgetIdentifier forWidgetIdiom:(int)widgetIdiom bundlePath:(id)path;
-(id)_newWidgetViewControllerWithIdentifier:(id)identifier forWidgetIdiom:(int)widgetIdiom bundlePath:(id)path;
@end

