/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWidgetViewControllerHost.h"

@class _SBWidgetViewControllerHost_Proxy, NSMutableArray;

__attribute__((visibility("hidden")))
@interface _SBWidgetViewControllerHostOutOfProcess : SBWidgetViewControllerHost {
	_SBWidgetViewControllerHost_Proxy* _proxy;
	NSMutableArray* _requestQueue;
}
@property(retain, nonatomic, setter=_setProxy:) _SBWidgetViewControllerHost_Proxy* _proxy;
+(id)requestViewController:(id)controller context:(id)context handler:(id)handler;
-(void)hostDidDismiss;
-(void)hostWillDismiss;
-(void)hostDidPresent;
-(void)hostWillPresent;
-(void)requestPreferredViewSizeWithHandler:(id)handler;
-(void)_performOrEnqueueRequest:(id)request;
-(void)_performPendingRequestsIfPossible;
-(void)viewDidLoad;
-(void)loadView;
-(void)dealloc;
-(id)initWithWidgetIdentifier:(id)widgetIdentifier forWidgetIdiom:(int)widgetIdiom bundlePath:(id)path;
@end

