/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"

@class NSMapTable, NSHashTable;

__attribute__((visibility("hidden")))
@interface SBActivationContext : XXUnknownSuperclass <NSCopying> {
	NSMapTable* _displayValues;
	NSMapTable* _activationValues;
	NSMapTable* _deactivationValues;
	NSHashTable* _displayFlags;
	NSHashTable* _activationFlags;
	NSHashTable* _deactivationFlags;
}
@property(copy, nonatomic) NSHashTable* deactivationFlags;
@property(copy, nonatomic) NSHashTable* activationFlags;
@property(copy, nonatomic) NSHashTable* displayFlags;
@property(copy, nonatomic) NSMapTable* deactivationValues;
@property(copy, nonatomic) NSMapTable* activationValues;
@property(copy, nonatomic) NSMapTable* displayValues;
+(id)newFlagTable;
+(id)newValueTable;
+(id)contextFromDisplay:(id)display;
-(id)_deactivationSettingsDescription;
-(id)_descriptionForDeactivationSetting:(unsigned)deactivationSetting;
-(id)_activationSettingsDescription;
-(id)_descriptionForActivationSetting:(unsigned)activationSetting;
-(id)_displaySettingsDescription;
-(id)_descriptionForDisplaySetting:(unsigned)displaySetting;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(BOOL)deactivationFlag:(unsigned)flag;
-(id)deactivationValue:(unsigned)value;
-(void)setDeactivationSetting:(unsigned)setting value:(id)value;
-(void)setDeactivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearDeactivationSettings;
-(BOOL)activationFlag:(unsigned)flag;
-(id)activationValue:(unsigned)value;
-(void)setActivationSetting:(unsigned)setting value:(id)value;
-(void)setActivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearActivationSettings;
-(BOOL)displayFlag:(unsigned)flag;
-(id)displayValue:(unsigned)value;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithDisplay:(id)display;
@end

