/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIActiveOrientationObserver.h"

@class UIWindow, UIViewController, NSMutableSet, SBAppSliderWindow;

__attribute__((visibility("hidden")))
@interface SBAppSliderWindowController : XXUnknownSuperclass <SBUIActiveOrientationObserver> {
	SBAppSliderWindow* _window;
	UIViewController* _rootViewController;
	int _trueWindowOrientation;
	int _overrideWindowOrientation;
	NSMutableSet* _rotationPreventionReasons;
}
@property(readonly, assign, nonatomic) UIWindow* window;
@property(retain, nonatomic) UIViewController* rootViewController;
-(void)activeInterfaceOrientationDidChangeToOrientation:(int)activeInterfaceOrientation willAnimateWithDuration:(double)duration fromOrientation:(int)orientation;
-(void)activeInterfaceOrientationWillChangeToOrientation:(int)activeInterfaceOrientation;
-(void)_rotateIfNecessaryTo:(int)to withDuration:(double)duration forOverride:(BOOL)override;
-(void)_setTrueWindowOrientation:(int)orientation;
-(void)_setOverrideWindowOrientation:(int)orientation;
-(BOOL)_shouldAllowRotation:(BOOL)rotation;
-(BOOL)_hasOrientationOverride;
-(void)setAllowRotation:(BOOL)rotation forReason:(id)reason;
-(void)clearOverrideWindowOrientation;
-(void)overrideWindowOrientation:(int)orientation;
-(int)windowOrientationWithoutOverrides;
-(int)windowOrientation;
-(void)_windowDidBecomeVisible:(id)_window;
-(void)dealloc;
-(id)initWithRootViewController:(id)rootViewController;
@end

