/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBFParallaxSettings, SBFLockScreenWallpaperParallaxSettings, SBFHomeScreenWallpaperParallaxSettings;

__attribute__((visibility("hidden")))
@interface SBAppParallaxSettings : XXUnknownSuperclass {
	SBFLockScreenWallpaperParallaxSettings* _lockscreenWallpaperSettings;
	SBFHomeScreenWallpaperParallaxSettings* _homescreenWallpaperSettings;
	SBFParallaxSettings* _iconSettings;
	SBFParallaxSettings* _iconBadgeSettings;
}
@property(retain) SBFParallaxSettings* iconBadgeSettings;
@property(retain) SBFParallaxSettings* iconSettings;
@property(retain) SBFHomeScreenWallpaperParallaxSettings* homescreenWallpaperSettings;
@property(retain) SBFLockScreenWallpaperParallaxSettings* lockscreenWallpaperSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

