/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAwayListItem.h"

@class BBBulletin, BBObserver, NSMutableArray, NSString, NSDate, UIImage;

__attribute__((visibility("hidden")))
@interface SBAwayBulletinListItem : SBAwayListItem {
	NSMutableArray* _bulletins;
	int _personID;
	NSString* _contactInfo;
	BBObserver* _observer;
	NSDate* _sortDate;
	NSDate* _displayDate;
	NSString* _message;
	UIImage* _listItemImage;
	BBBulletin* _activeBulletin;
}
@property(retain) BBBulletin* activeBulletin;
-(BOOL)overridesQuietMode;
-(BOOL)isCritical;
-(BOOL)inertWhenLocked;
-(id)observer;
-(int)snoozeButtonindex;
-(BOOL)wantsHighlightOnInsert;
-(void)buttonPressed;
-(BOOL)canBeClearedByNotificationCenter;
-(BOOL)canSnooze;
-(BOOL)isVIP;
-(BOOL)canCoalesceWithBulletin:(id)bulletin;
-(BOOL)hasSamePersonAsBulletin:(id)bulletin;
-(id)attachmentText;
-(id)attachmentImageForKey:(id)key;
-(id)iconImage;
-(id)description;
-(unsigned)maxMessageLines;
-(id)subtitle;
-(id)publishDate;
-(id)date;
-(BOOL)hasEventDate;
-(id)title;
-(id)message;
-(id)bulletins;
-(id)sortDate;
-(BOOL)containsBulletinWithID:(id)anId;
-(void)modifyBulletin:(id)bulletin;
-(void)removeAllBulletins;
-(void)removeBulletin:(id)bulletin;
-(void)addBulletin:(id)bulletin;
-(void)_updateButtonLabels;
-(void)_updateMessage;
-(BOOL)_suppressesMessageForPrivacy;
-(void)_updateImage;
-(void)_updateDisplayDate;
-(void)_updateSortDate;
-(void)_updateActiveBulletin;
-(id)sortedBulletins;
-(void)_update;
-(id)bulletinWithID:(id)anId;
-(void)dealloc;
-(id)initWithBulletin:(id)bulletin andObserver:(id)observer;
@end

