/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBTestRecipe.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBadgeCountRecipe : XXUnknownSuperclass <SBTestRecipe> {
}
+(id)title;
-(void)_changeBadge:(int)badge;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
@end

