/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBWorkStoreObserver.h"

@class SBWorkStore, NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBBackgroundMultitaskingManager : XXUnknownSuperclass <SBWorkStoreObserver> {
	NSMutableDictionary* _appToBackgroundTasks;
	NSMutableDictionary* _backgroundFetchTaskValueToWatchdoggableCompletion;
	NSObject<OS_dispatch_queue>* _queue;
	SBWorkStore* _pendingWorkStore;
	double _watchdogTimeout;
}
@property(readonly, assign, nonatomic) double watchdogTimeout;
+(BOOL)shouldFakeAdoption;
+(id)sharedInstance;
-(void)handlePushNotificationFromApplication:(id)application userInfo:(id)info priority:(int)priority completion:(id)completion;
-(id)_opportunisticallyUpdateApplications:(id)applications trigger:(unsigned)trigger;
-(void)_performPendingWorkForBundleID:(id)bundleID;
-(BOOL)_launchAppForUpdating:(id)updating trigger:(unsigned)trigger pushNotificationUserInfo:(id)info withWatchdoggableCompletion:(id)watchdoggableCompletion;
-(void)_startBackgroundFetchTaskForApplication:(id)application trigger:(unsigned)trigger sequenceNumber:(int)number withWatchdoggableCompletion:(id)watchdoggableCompletion;
-(void)queue_startBackgroundFetchTaskForApplication:(id)application trigger:(unsigned)trigger sequenceNumber:(int)number withWatchdoggableCompletion:(id)watchdoggableCompletion;
-(void)_backgroundTaskFinished:(id)finished forApplication:(id)application;
-(void)queue_backgroundTaskFinished:(id)finished forApplication:(id)application;
-(void)_invalidateBackgroundTasksForApplication:(id)application;
-(void)queue_invalidateBackgroundTasksForApplication:(id)application;
-(void)_watchdogCompletionForBackgroundFetchTaskValue:(id)backgroundFetchTaskValue;
-(void)queue_fireWatchdoggableCompletionForBackgroundFetchTaskValue:(id)backgroundFetchTaskValue;
-(void)queue_bearTrap_AppWasSuspended:(id)suspended;
-(void)_appStateDidChange:(id)_appState;
-(void)_startBackgroundFetchForNotification:(id)notification;
-(void)_appFinishedBackgroundUpdating:(id)updating;
-(void)queue_appFinishedBackgroundUpdating:(id)updating userInfo:(id)info;
-(void)workDidChange:(id)work;
-(void)application:(id)application didSetMinimumFetchInterval:(double)interval;
-(int)nextSequenceNumber;
-(id)init;
@end

