/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBBSectionInfo.h"

@class SBBBWidgetBulletinInfo;

__attribute__((visibility("hidden")))
@interface SBBBWidgetSectionInfo : SBBBSectionInfo {
	SBBBWidgetBulletinInfo* _widgetBulletinInfo;
}
@property(retain, nonatomic) SBBBWidgetBulletinInfo* widgetBulletinInfo;
-(BOOL)isWidgetSection;
-(id)identifier;
-(void)dealloc;
@end

