/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UICollisionBehaviorDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIDynamicItemBehavior, UICollisionBehavior, UIGravityBehavior, UIAttachmentBehavior;
@protocol SBBounceBehaviorDelegate, UIDynamicItem;

__attribute__((visibility("hidden")))
@interface SBBounceBehavior : XXUnknownSuperclass <UICollisionBehaviorDelegate> {
	float _midwayPosition;
	float _completionThreshold;
	CGRect _targetFrame;
	id<UIDynamicItem> _item;
	UIDynamicItemBehavior* _bodyBehavior;
	UICollisionBehavior* _collisionBehavior;
	UIGravityBehavior* _gravityBehavior;
	UIDynamicItemBehavior* _pushBehavior;
	UIAttachmentBehavior* _draggingBehavior;
	id<SBBounceBehaviorDelegate> _delegate;
	float _gravity;
	float _velocity;
	float _elasticity;
	float _friction;
	float _resistance;
	float _minVelocityToAssist;
	float _maxVelocityToAssist;
	float _maxVelocityAssistance;
	UIEdgeInsets _boundaryInsets;
}
@property(assign, nonatomic) UIEdgeInsets boundaryInsets;
@property(assign, nonatomic) float maxVelocityAssistance;
@property(assign, nonatomic) float maxVelocityToAssist;
@property(assign, nonatomic) float minVelocityToAssist;
@property(assign, nonatomic) float resistance;
@property(assign, nonatomic) float friction;
@property(assign, nonatomic) float elasticity;
@property(assign, nonatomic) float velocity;
@property(assign, nonatomic) float gravity;
@property(assign, nonatomic) id<SBBounceBehaviorDelegate> delegate;
-(void)collisionBehavior:(id)behavior beganContactForItem:(id)item withBoundaryIdentifier:(id)boundaryIdentifier atPoint:(CGPoint)point;
-(BOOL)allowsAnimatorToStop;
-(float)_maxVelocityToAssist;
-(float)_minVelocityToAssist;
-(float)_velocityAssistance;
-(BOOL)_shouldAssistWithVelocity:(float)velocity;
-(float)_adjustedVelocity:(float)velocity;
-(float)_itemOriginY;
-(BOOL)_itemStopped;
-(BOOL)_itemCompleted;
-(BOOL)_itemPastMidway;
-(float)_percentRemaining;
-(float)_percentComplete;
-(void)_removeDraggingBehavior;
-(void)_beginInteraction;
-(void)finishInteraction;
-(void)finishInteractionWithVelocity:(CGPoint)velocity;
-(void)finishInteractionWithVelocity:(CGPoint)velocity abortIfNotPastMidway:(BOOL)midway;
-(void)updateInteractionWithPoint:(CGPoint)point;
-(void)initiateInteractionFromPoint:(CGPoint)point;
-(void)bounce;
-(void)_setupCollisionBoundaries;
-(void)_frameCollisionBoundaryPoints:(CGPoint*)points;
-(BOOL)_isGravityDown;
-(BOOL)isActive;
-(void)dealloc;
-(id)initWithItem:(id)item;
-(id)initWithItem:(id)item targetFrame:(CGRect)frame;
@end

