/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinAlertHandler <NSObject>
-(void)handleEvent:(int)event withBulletin:(id)bulletin forRegistry:(id)registry;
-(BOOL)bindBulletin:(id)bulletin forRegistry:(id)registry;
@end

