/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RadiosPreferencesDelegate.h"
#import "SBUIControlCenterButtonDelegate.h"
#import "SBControlCenterSectionViewController.h"
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, BBSettingsGateway, BluetoothManager, RadiosPreferences;

__attribute__((visibility("hidden")))
@interface SBCCSettingsSectionController : SBControlCenterSectionViewController <SBUIControlCenterButtonDelegate, RadiosPreferencesDelegate> {
	NSMutableDictionary* _buttonsByID;
	BOOL _settingSupported[6];
	RadiosPreferences* _airplaneModeController;
	BBSettingsGateway* _settingsGateway;
	BOOL _dndEnabled;
	int _dndStatus;
	BluetoothManager* _btManager;
}
+(Class)viewClass;
-(void)_updateOrientationLockButtonState;
-(BOOL)_getOrientationLocked;
-(void)_setOrientationLocked:(BOOL)locked;
-(void)_tearDownOrientationLock;
-(void)_initOrientationLock;
-(void)_updateMuteButtonState;
-(BOOL)_getMuted;
-(void)_setMuted:(BOOL)muted;
-(void)_tearDownMute;
-(void)_initMute;
-(BOOL)_getDND;
-(void)_setDNDEnabled:(BOOL)enabled updateServer:(BOOL)server;
-(void)_setDNDStatus:(int)status;
-(void)_tearDownDND;
-(void)_initDND;
-(void)_updateBluetoothButtonState;
-(BOOL)_getBluetooth;
-(void)_setBluetoothEnabled:(BOOL)enabled;
-(void)_tearDownBluetooth;
-(void)_initBluetooth;
-(void)_updateWifiButtonState;
-(BOOL)_getWifi;
-(void)_setWifiEnabled:(BOOL)enabled;
-(void)_tearDownWifi;
-(void)_initWifi;
-(void)airplaneModeChanged;
-(BOOL)_getAirplaneMode;
-(void)_setAirplaneModeEnabled:(BOOL)enabled;
-(void)_tearDownAirplaneMode;
-(void)_initAirplaneMode;
-(void)buttonTapped:(id)tapped;
-(id)_buttonForSetting:(int)setting;
-(void)_addButtonForSetting:(int)setting;
-(id)_identifierForSetting:(int)setting;
-(void)viewWillLayoutSubviews;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)noteSettingsDidUpdate:(id)noteSettings;
-(id)view;
-(CGSize)contentSizeForOrientation:(int)orientation;
-(id)sectionIdentifier;
-(void)dealloc;
-(id)init;
@end

