/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBControlCenterObserver.h"
#import "SpringBoard-Structs.h"

@class UIViewController, SBCCSettingsSectionController, SBControlCenterGrabberView, SBCCQuickLaunchSectionController, NSMutableArray, SBControlCenterSectionViewController;

__attribute__((visibility("hidden")))
@interface SBControlCenterContentView : XXUnknownSuperclass <SBControlCenterObserver> {
	NSMutableArray* _dividerViews;
	UIViewController* _viewController;
	SBControlCenterGrabberView* _grabberView;
	SBCCSettingsSectionController* _settingsSection;
	SBControlCenterSectionViewController* _brightnessSection;
	SBControlCenterSectionViewController* _mediaControlsSection;
	SBControlCenterSectionViewController* _airplaySection;
	SBCCQuickLaunchSectionController* _quickLaunchSection;
}
@property(retain, nonatomic) SBCCQuickLaunchSectionController* quickLaunchSection;
@property(retain, nonatomic) SBControlCenterSectionViewController* airplaySection;
@property(retain, nonatomic) SBControlCenterSectionViewController* mediaControlsSection;
@property(retain, nonatomic) SBControlCenterSectionViewController* brightnessSection;
@property(retain, nonatomic) SBCCSettingsSectionController* settingsSection;
@property(retain, nonatomic) SBControlCenterGrabberView* grabberView;
@property(assign, nonatomic) UIViewController* viewController;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)layoutSubviews;
-(void)_iPhone_layoutSubviewsInBounds:(CGRect)bounds orientation:(int)orientation;
-(void)_iPad_layoutSubviewsInBounds:(CGRect)bounds orientation:(int)orientation;
-(void)updateSectionVisibility:(id)visibility animated:(BOOL)animated;
-(void)updateEnabledSections;
-(void)_removeSectionController:(id)controller;
-(void)_addSectionController:(id)controller;
-(float)contentHeightForOrientation:(int)orientation;
-(id)_separatorAtIndex:(unsigned)index;
-(id)_allSections;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

