/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDateLabelDelegate.h"
#import "SBUIBannerView.h"
#import "SpringBoard-Structs.h"

@class SBDefaultBannerTextView, UIImageView, SBUIBannerContext, UILabel;
@protocol SBBulletinDateLabel, SBDefaultBannerViewSource;

__attribute__((visibility("hidden")))
@interface SBDefaultBannerView : XXUnknownSuperclass <SBDateLabelDelegate, SBUIBannerView> {
	SBUIBannerContext* _context;
	id<SBDefaultBannerViewSource> _viewSource;
	UIImageView* _iconImageView;
	UILabel<SBBulletinDateLabel>* _relevanceDateLabel;
	SBDefaultBannerTextView* _textView;
	UIImageView* _attachmentImageView;
	CGSize _grabberImageSize;
	UIImageView* _grabberImageView;
}
-(void)dateLabelDidChange:(id)dateLabel;
-(void)layoutSubviews;
-(id)bannerContext;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithContext:(id)context;
@end

