/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDismissOnlyAlertItem : XXUnknownSuperclass {
	NSString* _title;
	NSString* _body;
	double _autoDismissInterval;
}
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)performUnlockAction;
-(id)bodyText;
-(id)title;
-(void)setBodyText:(id)text;
-(void)setTitle:(id)title;
-(void)setAutoDismissInterval:(double)interval;
-(double)autoDismissInterval;
-(void)dealloc;
-(id)initWithTitle:(id)title body:(id)body;
@end

