/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBFakeStatusBarViewCache : XXUnknownSuperclass {
	NSMutableDictionary* _cachedStatusBarQueues;
}
-(void)dealloc;
-(id)barForKey:(id)key withGenerationBlockIfNecessary:(id)generationBlockIfNecessary;
-(void)recycleBar:(id)bar forKey:(id)key;
-(id)init;
@end

