/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol SBIconScrollViewDelegate;

__attribute__((visibility("hidden")))
@interface SBIconScrollView : XXUnknownSuperclass {
}
@property(assign, nonatomic) id<SBIconScrollViewDelegate> delegate;
-(void)setContentOffset:(CGPoint)offset;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(BOOL)cancelTouchTracking;
@end

