/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSMutableCopying.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"

@class NSString, UIFont;

__attribute__((visibility("hidden")))
@interface SBIconLabelImageParameters : XXUnknownSuperclass <NSCopying, NSMutableCopying> {
	UIFont* _font;
	NSString* _text;
	BOOL _containsNonLatinLikeCharacters;
	BOOL _containsEmoji;
	BOOL _canEllipsize;
	CGSize _maxSize;
	int _style;
}
@property(readonly, assign, nonatomic) int style;
@property(readonly, assign, nonatomic) BOOL containsEmoji;
@property(readonly, assign, nonatomic) BOOL containsNonLatinLikeCharacters;
@property(readonly, assign, nonatomic) BOOL canEllipsize;
@property(readonly, assign, nonatomic) UIFont* font;
@property(readonly, assign, nonatomic) CGSize maxSize;
@property(readonly, assign, nonatomic) NSString* text;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(BOOL)colorspaceIsGrayscale;
-(void)dealloc;
-(id)initWithParameters:(id)parameters;
@end

