/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBFAnimationSettings;

__attribute__((visibility("hidden")))
@interface SBIconZoomSettings : XXUnknownSuperclass {
	SBFAnimationSettings* _centralAnimationSettings;
}
@property(retain) SBFAnimationSettings* centralAnimationSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

