/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconListLayoutDelegate <NSObject>
@optional
-(void)iconListViewLayoutInvalidated:(id)invalidated;
-(void)iconListView:(id)view wouldHaveMovedIcon:(id)icon;
@end

