/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconIndexNode.h"
#import "SpringBoard-Structs.h"

@class NSHashTable, UIImage;

__attribute__((visibility("hidden")))
@interface SBIcon : XXUnknownSuperclass <SBIconIndexNode> {
	NSHashTable* _observers;
	id _badgeNumberOrString;
	unsigned _uninstalled : 1;
	UIImage* _cachedIconImages[14];
}
@property(readonly, assign, nonatomic) BOOL shouldWarmUp;
+(id)memoryMappedIconImageOfSize:(CGSize)size scale:(float)scale withDrawing:(id)drawing;
+(id)memoryMappedIconImageForIconImage:(id)iconImage;
+(id)_iconImageOfSize:(CGSize)size scale:(float)scale failGracefully:(BOOL)gracefully drawing:(id)drawing;
+(id)_iconImagesMemoryPool;
-(BOOL)canReceiveGrabbedIcon;
-(id)folderFallbackTitle;
-(id)folderTitleOptions;
-(id)uninstallAlertCancelTitle;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
-(id)uninstallAlertBodyForAppWithDocumentsInCloud;
-(id)uninstallAlertBody;
-(id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
-(id)uninstallAlertTitleForAppWithDocumentsInCloud;
-(id)uninstallAlertTitle;
-(BOOL)isUninstalled;
-(void)setUninstalled;
-(void)completeUninstall;
-(BOOL)allowsUninstall;
-(BOOL)progressIsPaused;
-(float)progressPercent;
-(int)progressState;
-(void)launchFromLocation:(int)location;
-(id)automationID;
-(BOOL)isRecentlyUpdated;
-(void)setBadge:(id)badge;
-(void)noteBadgeDidChange;
-(int)accessoryTypeForLocation:(int)location;
-(id)accessoryTextForLocation:(int)location;
-(id)badgeNumberOrString;
-(int)badgeValue;
-(void)reloadIconImagePurgingImageCache:(BOOL)cache;
-(void)reloadIconImage;
-(void)purgeCachedImages;
-(id)gridCellImage;
-(id)getGenericIconImage:(int)image;
-(id)getUnmaskedIconImage:(int)image;
-(id)getIconImage:(int)image;
-(id)getStandardIconImageForLocation:(int)location;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(id)generateIconImage:(int)image;
-(BOOL)launchEnabled;
-(id)tags;
-(BOOL)matchesEntity:(id)entity;
-(int)localizedCompareDisplayNames:(id)names;
-(BOOL)canEllipsizeLabel;
-(id)displayName;
-(void)localeChanged;
-(BOOL)matchesRepresentation:(id)representation;
-(id)representation;
-(void)dealloc;
-(id)init;
-(int)iconFormatForLocation:(int)location;
-(BOOL)hasCachedImageForLocation:(int)location;
-(id)nodeDescriptionWithPrefix:(id)prefix;
-(void)removeNodeObserver:(id)observer;
-(void)addNodeObserver:(id)observer;
-(id)nodesAlongIndexPath:(id)path consumedIndexes:(unsigned)indexes;
-(id)indexPathsForContainedNodeIdentifier:(id)containedNodeIdentifier prefixPath:(id)path;
-(id)containedNodeIdentifiers;
-(BOOL)containsNodeIdentifier:(id)identifier;
-(id)nodeIdentifier;
-(BOOL)hasObserver:(id)observer;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(id)description;
-(id)application;
-(BOOL)isApplicationIcon;
-(BOOL)isBookmarkIcon;
-(id)appPlaceholder;
-(BOOL)isDownloadingIcon;
-(BOOL)isUserInstalledApplicationIcon;
-(BOOL)isWebApplicationIcon;
-(BOOL)hasFolderIconView;
-(id)folder;
-(BOOL)isFolderIcon;
-(id)applicationBundleID;
-(id)webClip;
-(id)leafIdentifier;
-(BOOL)isLeafIcon;
-(Class)iconImageViewClassForLocation:(int)location;
-(Class)iconViewClassForLocation:(int)location;
-(void)_notifyLaunchEnabledDidChange;
-(void)_notifyAccessoriesDidUpdate;
-(void)_notifyImageDidUpdate;
-(BOOL)iconAppearsInNewsstand;
-(BOOL)isNewsstandApplicationIcon;
-(BOOL)isNewsstandIcon;
-(BOOL)isEmptyPlaceholder;
-(BOOL)isGrabbedIconPlaceholder;
-(BOOL)isPlaceholder;
@end

