/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUnlockActionHandler.h"


@protocol SBLockScreenNotificationViewDelegate <SBUnlockActionHandler>
-(id)lockScreenScrollView;
-(void)noteUnlockActionChanged:(id)changed;
@end

