/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenTestPluginSettings : XXUnknownSuperclass {
	BOOL _enablePlugin;
	BOOL _enableLostModePlugin;
	BOOL _showDateView;
	BOOL _showDate;
	BOOL _disableOnUnlock;
	BOOL _showCamera;
	BOOL _showBackgroundView;
	unsigned _overlayStyle;
	unsigned _notificationBehavior;
}
@property(assign) BOOL showBackgroundView;
@property(assign) BOOL showCamera;
@property(assign) BOOL disableOnUnlock;
@property(assign) BOOL showDate;
@property(assign) BOOL showDateView;
@property(assign) unsigned notificationBehavior;
@property(assign) unsigned overlayStyle;
@property(assign) BOOL enableLostModePlugin;
@property(assign) BOOL enablePlugin;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

