/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewController.h"
#import "SBLockOverlayViewDelegate.h"

@class NSString, SBLockScreenInfoOverlayView;
@protocol SBLockScreenInfoOverlayDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenInfoOverlayViewController : SBLockOverlayViewController <SBLockOverlayViewDelegate> {
	SBLockScreenInfoOverlayView* _overlayView;
	NSString* _title;
}
@property(assign, nonatomic) id<SBLockScreenInfoOverlayDelegate> delegate;
-(void)handleTapGestureFromView:(id)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithTitle:(id)title;
@end

