/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewController.h"

@class SBAwayViewPluginController;

__attribute__((visibility("hidden")))
@interface SBLockScreenPluginOverlayViewController : SBLockOverlayViewController {
	SBAwayViewPluginController* _pluginController;
}
-(id)_newOverlayView;
-(void)loadView;
-(void)dealloc;
-(id)initWithPluginController:(id)pluginController;
@end

