/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenPasscodeSettings : XXUnknownSuperclass {
	int _scrollBehavior;
	float _fixedHysteresis;
	float _percentOfNextButtonIncluded;
}
@property(assign, nonatomic) float percentOfNextButtonIncluded;
@property(assign, nonatomic) float fixedHysteresis;
@property(assign, nonatomic) int scrollBehavior;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

