/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class SBAlertItem;

__attribute__((visibility("hidden")))
@interface SBMiniAlertItemTestRecipe : XXUnknownSuperclass <SBTestRecipe> {
	SBAlertItem* _item;
}
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
@end

