/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconLabelImageParameters.h"
#import "SpringBoard-Structs.h"

@class NSString, UIFont;

__attribute__((visibility("hidden")))
@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters {
}
@property(assign, nonatomic) int style;
@property(assign, nonatomic) BOOL canEllipsize;
@property(assign, nonatomic) BOOL containsEmoji;
@property(assign, nonatomic) BOOL containsNonLatinLikeCharacters;
@property(retain, nonatomic) UIFont* font;
@property(assign, nonatomic) CGSize maxSize;
@property(copy, nonatomic) NSString* text;
-(id)copy;
@end

