/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolder.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandFolder : SBFolder {
}
-(id)nodeIdentifier;
-(void)_setDisplayNameFromRepresentation:(id)representation;
-(BOOL)canAddIcon;
-(id)folderType;
-(BOOL)canEditDisplayName;
-(BOOL)canRemoveIcons;
-(BOOL)shouldRemoveWhenEmpty;
-(BOOL)isNewsstandFolder;
-(Class)listViewClass;
-(Class)listModelClass;
-(void)setIsOpen:(BOOL)open;
-(id)icon;
-(id)init;
-(Class)controllerClass;
@end

