/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBulletinActionHandler.h"
#import "SBWidgetViewControllerHostDelegate.h"
#import "SpringBoard-Structs.h"


@protocol SBNotificationCenterViewControllerDelegate <SBWidgetViewControllerHostDelegate, SBBulletinActionHandler>
@optional
-(id)widgetViewControllerHostDelegate:(id)delegate;
@end

