/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinObserverViewController.h"

@class NSMutableDictionary, NSMutableArray, NSArray;
@protocol SBBulletinActionHandler;

__attribute__((visibility("hidden")))
@interface SBNotificationsModeViewController : SBBulletinObserverViewController {
	struct {
		unsigned isContentLayoutValid : 1;
		unsigned isSegmentLayoutValid : 1;
		unsigned isRequestHandlingEnabled : 1;
		unsigned hasViewEverAppeared : 1;
	} _notificationsModeViewControllerDelegateFlags;
	NSMutableArray* _orderedSectionIDs;
	NSMutableDictionary* _sectionIDsToOrderedBulletins;
}
@property(readonly, assign, nonatomic) NSMutableDictionary* sectionIDsToOrderedBulletins;
@property(readonly, assign, nonatomic) NSArray* orderedSectionIDs;
@property(assign, nonatomic) id<SBBulletinViewControllerDelegate, SBBulletinActionHandler> delegate;
-(BOOL)handleActionForBulletin:(id)bulletin;
-(int)bulletinViewController:(id)controller replacementAnimationForBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller removalAnimationForBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller insertionAnimationForBulletin:(id)bulletin inSection:(id)section;
-(void)updateForChangeInMessagePrivacy;
-(void)hostWillPresent;
-(void)updateSection:(id)section withParameters:(id)parameters;
-(void)updateSection:(id)section withInfo:(id)info;
-(void)_updateSectionForChangeInNumberOfLines:(id)lines;
-(void)_updateSection:(id)section withLockState:(BOOL)lockState;
-(void)_updateSectionForChangeInMessagePrivacyIfNecessary:(id)messagePrivacyIfNecessary;
-(void)_updateSectionForChangeInLockScreenVisibility:(id)lockScreenVisibility withLockState:(BOOL)lockState updatedSubsectionIDs:(id)ids;
-(void)_updateSectionForChangeInLockScreenVisibility:(id)lockScreenVisibility withProcessingBlock:(id)processingBlock;
-(void)populateBulletinInfo:(id)info inSection:(id)section;
-(id)infoForBulletinInfo:(id)bulletinInfo inSection:(id)section;
-(void)commitMoveOfBulletin:(id)bulletin inSection:(id)section beforeBulletin:(id)bulletin3 inSection:(id)section4;
-(void)commitReplacementWithBulletin:(id)bulletin ofBulletin:(id)bulletin2 inSection:(id)section;
-(void)commitRemovalOfBulletin:(id)bulletin fromSection:(id)section;
-(void)commitInsertionOfBulletin:(id)bulletin beforeBulletin:(id)bulletin2 inSection:(id)section forFeed:(unsigned)feed;
-(void)_updateSectionOrderForOperationInSection:(id)section;
-(void)_sortBulletins:(id)bulletins forSection:(id)section;
-(void)commitReplacementWithSection:(id)section ofSection:(id)section2;
-(void)commitMoveOfSection:(id)section beforeSection:(id)section2;
-(void)commitRemovalOfSection:(id)section;
-(void)commitInsertionOfSection:(id)section beforeSection:(id)section2;
-(void)_sortSectionIDs;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(id)initWithObserverFeed:(unsigned)observerFeed;
@end

