/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSizeObservingViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBBulletinViewControllerDelegate.h"
#import "SBNotificationCenterWidgetHost.h"
#import "SBBulletinActionHandler.h"

@class SBBulletinObserverViewController, SBChevronView, SBModeViewController, SBNotificationCenterSeparatorView, _UIBackdropView, UIView, UIStatusBar;
@protocol SBNotificationCenterViewControllerDelegate, SBWidgetViewControllerHostDelegate;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterViewController : XXUnknownSuperclass <SBBulletinViewControllerDelegate, SBSizeObservingViewDelegate, SBNotificationCenterWidgetHost, SBBulletinActionHandler> {
	id<SBNotificationCenterViewControllerDelegate> _delegate;
	UIView* _clippingView;
	UIView* _containerView;
	UIView* _contentView;
	UIView* _backgroundView;
	UIView* _coveredContentContainer;
	SBNotificationCenterSeparatorView* _bottomSeparator;
	SBModeViewController* _modeController;
	SBBulletinObserverViewController* _todayViewController;
	SBBulletinObserverViewController* _allModeViewController;
	SBBulletinObserverViewController* _missedModeViewController;
	UIStatusBar* _statusBar;
	SBChevronView* _grabberView;
	UIView* _grabberContentView;
	UIView* _grabberBackgroundView;
	SBChevronView* _registeredGrabberView;
	CGRect _grabberContentViewFrameForRegisteredGrabber;
	id _registeredGrabberHideBlock;
	struct {
		unsigned blursBackground : 1;
		unsigned showsBackground : 1;
		unsigned isBackgroundValid : 1;
		unsigned isGrabberEnabled : 1;
		unsigned isGrabberLockEngaged : 1;
		unsigned viewHitTestsAsOpaque : 1;
		unsigned isViewHitTestingValid : 1;
	} _notificationCenterViewControllerFlags;
}
@property(assign, nonatomic) id<SBWidgetViewControllerHostDelegate> widgetDelegate;
@property(readonly, assign, nonatomic) SBChevronView* grabberView;
@property(retain, nonatomic) UIView* coveredContentSnapshot;
@property(readonly, assign, nonatomic) _UIBackdropView* backdropView;
@property(assign, nonatomic) BOOL blursBackground;
@property(assign, nonatomic) BOOL showsBackground;
@property(assign, nonatomic, getter=isGrabberViewEnabled) BOOL grabberViewEnabled;
@property(readonly, assign, nonatomic) CGRect contentFrame;
@property(assign, nonatomic) UIEdgeInsets clippingInsets;
@property(assign, nonatomic) float contentViewAlpha;
@property(assign, nonatomic, getter=isSuppressingNotificationUpdates) BOOL suppressesNotificationUpdates;
@property(assign, nonatomic) id<SBNotificationCenterViewControllerDelegate> delegate;
+(id)_localizableTitleForBulletinViewControllerOfClass:(Class)aClass;
+(id)grayControlInteractionTintColor;
-(void)runScrollTest:(id)test iterations:(int)iterations delta:(int)delta;
-(BOOL)handleActionForBulletin:(id)bulletin;
-(void)hostDidDismiss;
-(void)hostWillDismiss;
-(void)hostDidPresent;
-(void)hostWillPresent;
-(void)updateForChangeInMessagePrivacy;
-(void)_setContainerFrame:(CGRect)frame;
-(CGRect)_containerFrame;
-(void)dismissGrabberView;
-(void)presentGrabberView;
-(CGRect)_grabberContentViewFrameForDefaultGrabberPresentation;
-(CGRect)_grabberContentViewFrameForRegisteredGrabber;
-(CGRect)positionContentForTouchAtLocation:(CGPoint)location;
-(void)_setViewHitTestAsOpaque:(BOOL)opaque;
-(void)_reloadAllWidgets;
-(void)disableGrabberLock;
-(BOOL)isGrabberLocked;
-(void)_configureGrabberForSoloMode:(BOOL)soloMode;
-(id)unregisterSharedGrabberView;
-(void)registerSharedGrabberView:(id)view withHideBlock:(id)hideBlock;
-(void)_register:(BOOL)aRegister grabberView:(id)view withHideBlock:(id)hideBlock;
-(CGRect)revealRectForBulletin:(id)bulletin;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillLayoutSubviews;
-(void)sizeObservingView:(id)view didChangeSize:(CGSize)size;
-(void)viewDidLoad;
-(void)loadView;
-(void)_configureModeControllerView;
-(void)_loadBottomSeparator;
-(void)_loadGrabberContentView;
-(id)_newGrabberView;
-(void)_updateContrastSettingsForBottomSeparator;
-(void)_updateContrastSettingsForGrabberView;
-(void)_loadStatusBar;
-(void)_loadContentView;
-(void)_loadContainerView;
-(void)_loadClippingView;
-(void)_configureView;
-(void)_validateBackgroundViewIfNecessary;
-(id)_newBackgroundView;
-(void)_loadContentViewControllersForCurrentState;
-(id)_missedModeViewControllerCreateIfNecessary:(BOOL)necessary;
-(id)_allModeViewControllerCreateIfNecessary:(BOOL)necessary;
-(id)_todayViewControllerCreateIfNecessary:(BOOL)necessary;
-(id)_newBulletinObserverViewControllerOfClass:(Class)aClass;
-(void)_backgroundContrastDidChange:(id)_backgroundContrast;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

