/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBNotificationsModeViewController.h"
#import "UIGestureRecognizerDelegatePrivate.h"

@class SBNotificationCenterTouchEater, SBNotificationsSectionHeaderView;

__attribute__((visibility("hidden")))
@interface SBNotificationsAllModeViewController : SBNotificationsModeViewController <UIGestureRecognizerDelegatePrivate> {
	SBNotificationCenterTouchEater* _clearButtonTouchEater;
	SBNotificationsSectionHeaderView* _headerViewCurrentlyInClearState;
}
-(void)commitReloadOfSections:(id)sections;
-(id)infoForBulletin:(id)bulletin inSection:(id)section;
-(id)infoForBulletinSection:(id)bulletinSection;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)_handleEatenTouch:(id)touch;
-(void)_setHeaderViewCurrentlyInClearState:(id)clearState;
-(id)_headerViewCurrentlyInClearState;
-(UIEdgeInsets)bulletinViewControllerContentInsetsForMode:(int)mode;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)_installClearButtonTouchEater;
-(int)widgetIdiomForCategory:(int)category;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

