/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDateLabelDelegate.h"
#import "SpringBoard-Structs.h"

@class UIImageView, UIColor, UILabel, NSString, UIButton, UIView, UIImage;
@protocol SBBulletinDateLabel;

__attribute__((visibility("hidden")))
@interface SBNotificationCell : XXUnknownSuperclass <SBDateLabelDelegate> {
	UIView* _realContentView;
	UIImageView* _iconImageView;
	UILabel* _primaryLabel;
	UILabel* _subtitleLabel;
	UILabel* _secondaryLabel;
	UILabel<SBBulletinDateLabel>* _relevanceDateLabel;
	UILabel<SBBulletinDateLabel>* _eventDateLabel;
	UIButton* _actionButton;
	UIImageView* _attachmentView;
	CGSize _attachmentSize;
	BOOL _secondaryTextNumberOfLinesIsUpperBound;
	unsigned _secondaryTextNumberOfLines;
	float _secondaryTextHeight;
	UIImage* _icon;
}
@property(readonly, assign, nonatomic) UIView* attachmentView;
@property(assign, nonatomic) float secondaryTextHeight;
@property(assign, nonatomic) float attachmentAlpha;
@property(assign, nonatomic) float iconAlpha;
@property(assign, nonatomic) float eventDateAlpha;
@property(assign, nonatomic) float relevanceDateAlpha;
@property(assign, nonatomic) float secondaryTextAlpha;
@property(assign, nonatomic) float subtitleTextAlpha;
@property(assign, nonatomic) float primaryTextAlpha;
@property(retain, nonatomic) UIColor* eventDateColor;
@property(retain, nonatomic) UIColor* relevanceDateColor;
@property(retain, nonatomic) UIColor* secondaryTextColor;
@property(retain, nonatomic) UIColor* subtitleTextColor;
@property(retain, nonatomic) UIColor* primaryTextColor;
@property(readonly, assign, nonatomic) BOOL secondaryTextNumberOfLinesIsUpperBound;
@property(readonly, assign, nonatomic) unsigned secondaryTextNumberOfLines;
@property(retain, nonatomic) UIButton* actionButton;
@property(retain, nonatomic) UILabel<SBBulletinDateLabel>* eventDateLabel;
@property(retain, nonatomic) UILabel<SBBulletinDateLabel>* relevanceDateLabel;
@property(readonly, assign, nonatomic) UILabel* secondaryLabel;
@property(readonly, assign, nonatomic) UILabel* subtitleLabel;
@property(readonly, assign, nonatomic) UILabel* primaryLabel;
@property(copy, nonatomic) NSString* secondaryText;
@property(copy, nonatomic) NSString* subtitleText;
@property(copy, nonatomic) NSString* primaryText;
@property(readonly, assign, nonatomic) UIView* iconView;
@property(retain, nonatomic) UIImage* icon;
@property(readonly, assign, nonatomic) CGRect contentBounds;
@property(readonly, assign, nonatomic) UIView* realContentView;
+(float)paddingBetweenTitleAndRelevanceDate;
+(float)xInsetForOrientation:(int)orientation;
+(float)contentWidthWithRowWidth:(float)rowWidth andAttachmentSize:(CGSize)size;
+(void)setupEventDateLabel:(id)label;
+(void)setupRelevanceDateLabel:(id)label;
+(id)defaultColorForEventDate;
+(id)defaultColorForRelevanceDate;
+(id)defaultColorForSecondaryText;
+(id)defaultColorForSubtitleText;
+(id)defaultColorForPrimaryText;
+(id)defaultFontForEventDate;
+(id)defaultFontForRelevanceDate;
+(id)defaultFontForSecondaryText;
+(id)defaultFontForSubtitleText;
+(id)defaultFontForPrimaryText;
+(float)actionButtonPaddingLeft;
+(float)iconPaddingLeft;
+(float)primaryPaddingRight;
+(float)primaryPaddingLeft;
-(void)layoutSubviews;
-(void)setAttachmentImage:(id)image;
-(void)dateLabelDidChange:(id)dateLabel;
-(void)setSecondaryTextNumberOfLines:(unsigned)lines treatAsUpperBound:(BOOL)bound;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

