/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBResponderTouchDelegate <NSObject>
-(void)responder:(id)responder touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)responder:(id)responder touchesEnded:(id)ended withEvent:(id)event;
-(void)responder:(id)responder touchesBegan:(id)began withEvent:(id)event;
@end

