/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBRelativeDateTimerDelegate.h"
#import "SBDefaultDateLabel.h"

@class SBRelativeDateTimer;

__attribute__((visibility("hidden")))
@interface SBRelativeDateLabel : SBDefaultDateLabel <SBRelativeDateTimerDelegate> {
	SBRelativeDateTimer* _relativeDateTimer;
	unsigned _value;
	int _resolution;
	int _comparedToNow;
}
-(void)timerFiredWithValue:(unsigned)value forResolution:(int)resolution comparedToNow:(int)now;
-(id)constructLabelString;
-(void)prepareForReuse;
-(void)dealloc;
-(void)setTimeZoneRelativeStartDate:(id)date absoluteStartDate:(id)date2;
@end

