/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBRelaunchAppWorkspaceTransaction.h"


__attribute__((visibility("hidden")))
@interface SBRelaunchBuddyWorkspaceTransaction : SBRelaunchAppWorkspaceTransaction {
}
-(void)_commit;
-(id)_setupAnimationForApp:(id)app;
@end

