/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppSliderSettings, SBAlertItemsSettings, SBCarDisplaySettings, SBFolderSettings, SBNotificationCenterSettings, SBLockScreenSettings, SBFWallpaperSettings, SBLockScreenTestPluginSettings, NSString, SBLegibilitySettings, SBFadeAnimationSettings, SBControlCenterSettings, SBRootZoomSettings, SBAppParallaxSettings, SBIconColorSettings;

__attribute__((visibility("hidden")))
@interface SBRootSettings : XXUnknownSuperclass {
	BOOL _preventLockover;
	BOOL _slowSpringAnimations;
	SBAppParallaxSettings* _parallaxSettings;
	SBFolderSettings* _folderSettings;
	SBRootZoomSettings* _rootZoomSettings;
	SBControlCenterSettings* _controlCenterSettings;
	SBAppSliderSettings* _appSliderSettings;
	SBLockScreenSettings* _lockScreenSettings;
	SBCarDisplaySettings* _carDisplaySettings;
	SBLockScreenTestPluginSettings* _lockScreenTestPluginSettings;
	SBIconColorSettings* _iconColorSettings;
	SBFadeAnimationSettings* _fadeAnimationSettings;
	SBAlertItemsSettings* _alertItemsSettings;
	SBNotificationCenterSettings* _notificationCenterSettings;
	SBLegibilitySettings* _legibilitySettings;
	SBFWallpaperSettings* _wallpaperSettings;
	NSString* _testRecipeClassName;
}
@property(assign) BOOL slowSpringAnimations;
@property(assign) BOOL preventLockover;
@property(retain) NSString* testRecipeClassName;
@property(retain) SBFWallpaperSettings* wallpaperSettings;
@property(retain) SBLegibilitySettings* legibilitySettings;
@property(retain) SBNotificationCenterSettings* notificationCenterSettings;
@property(retain) SBAlertItemsSettings* alertItemsSettings;
@property(retain) SBFadeAnimationSettings* fadeAnimationSettings;
@property(retain) SBIconColorSettings* iconColorSettings;
@property(retain) SBLockScreenTestPluginSettings* lockScreenTestPluginSettings;
@property(retain) SBCarDisplaySettings* carDisplaySettings;
@property(retain) SBLockScreenSettings* lockScreenSettings;
@property(retain) SBAppSliderSettings* appSliderSettings;
@property(retain) SBControlCenterSettings* controlCenterSettings;
@property(retain) SBRootZoomSettings* rootZoomSettings;
@property(retain) SBFolderSettings* folderSettings;
@property(retain) SBAppParallaxSettings* parallaxSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

