/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolderView.h"
#import "SBSearchGestureObserver.h"
#import "_UISettingsKeyObserver.h"
#import "SpringBoard-Structs.h"

@class TPLegacyLCDTextView, SBSearchViewController, SBDockIconListView, SBRootFolder, SBDockView, SBFParallaxSettings;

__attribute__((visibility("hidden")))
@interface SBRootFolderView : SBFolderView <_UISettingsKeyObserver, SBSearchGestureObserver> {
	SBDockView* _dockView;
	SBDockIconListView* _dockListView;
	TPLegacyLCDTextView* _idleTextView;
	SBFParallaxSettings* _parallaxSettings;
	float _searchGestureProgress;
	SBSearchViewController* _searchViewController;
}
@property(readonly, assign, nonatomic) SBSearchViewController* searchViewController;
@property(retain, nonatomic) SBRootFolder* folder;
-(void)searchGesture:(id)gesture changedPercentComplete:(float)complete;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)_configureParallax;
-(void)lcdTextViewCompletedScroll:(id)scroll;
-(void)setIdleText:(id)text;
-(void)layoutIconLists:(double)lists domino:(BOOL)domino forceRelayout:(BOOL)relayout;
-(void)tearDownListViews;
-(void)_updateEditingStateAnimated:(BOOL)animated;
-(void)resetIconListViews;
-(id)iconListViewAtPoint:(CGPoint)point;
-(id)iconListViewAtIndex:(unsigned)index;
-(void)_enableUserInteractionAfterSignificantAnimation;
-(void)_disableUserInteractionBeforeSignificantAnimation;
-(void)fadeContentForMinificationFraction:(float)minificationFraction;
-(void)fadeContentForMagnificationFraction:(float)magnificationFraction;
-(void)didAnimate;
-(void)willAnimate;
-(void)setDockVerticalStretch:(float)stretch;
-(void)setDockOffscreenFraction:(float)fraction;
-(id)dockView;
-(void)_layoutSubviews;
-(void)layoutViewsForSearch;
-(void)setOrientation:(int)orientation;
-(void)setNeedsLayout;
-(void)returnScalingView;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation forSnapshot:(BOOL)snapshot;
-(id)initWithFolder:(id)folder orientation:(int)orientation;
@end

