/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIFont;

__attribute__((visibility("hidden")))
@interface SBSearchTableViewContentSizeCache : XXUnknownSuperclass {
	UIFont* _bodyFont;
	UIFont* _caption1Font;
	UIFont* _boldCaption1Font;
	UIFont* _footnoteFont;
	float _baseHeight;
	float _footnoteFontLineHeight;
	float _footnoteFontAscender;
	float _bodyFontLineHeight;
	float _bodyFontAscender;
	float _caption1FontLineHeight;
	float _caption1FontAscender;
	float _emphasizedCaption1FontLineHeight;
	float _emphasizedCaption1FontAscender;
	float _summaryLineHeight;
}
@property(assign, nonatomic) float summaryLineHeight;
@property(assign, nonatomic) float emphasizedCaption1FontAscender;
@property(assign, nonatomic) float emphasizedCaption1FontLineHeight;
@property(assign, nonatomic) float caption1FontAscender;
@property(assign, nonatomic) float caption1FontLineHeight;
@property(assign, nonatomic) float bodyFontAscender;
@property(assign, nonatomic) float bodyFontLineHeight;
@property(assign, nonatomic) float footnoteFontAscender;
@property(assign, nonatomic) float footnoteFontLineHeight;
@property(assign, nonatomic) float baseHeight;
@property(retain, nonatomic) UIFont* footnoteFont;
@property(retain, nonatomic) UIFont* boldCaption1Font;
@property(retain, nonatomic) UIFont* caption1Font;
@property(retain, nonatomic) UIFont* bodyFont;
+(id)sharedInstance;
-(void)contentSizeDidChange;
@end

