/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchGestureObserver.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SPSearchAgentDelegate.h"
#import "UISearchBarDelegate.h"
#import "SBSearchHeaderDelegate.h"

@class UILabel, SBSearchResultsBackdropView, UITapGestureRecognizer, UIPanGestureRecognizer, UIImage, UIView, SBSearchHeader, UITableView;

__attribute__((visibility("hidden")))
@interface SBSearchViewController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, SPSearchAgentDelegate, SBSearchGestureObserver, UISearchBarDelegate, SBSearchHeaderDelegate> {
	SBSearchHeader* _searchHeader;
	SBSearchResultsBackdropView* _tableBackdrop;
	UITableView* _tableView;
	UILabel* _noResultsLabel;
	UIView* _touchStealingView;
	UITapGestureRecognizer* _tapRecognizer;
	UIPanGestureRecognizer* _panRecognizer;
	void* _addressBook;
	UIImage* _placeHolderImages[15];
	float _lastContentOffsetY;
	BOOL _scrollDown;
	BOOL _hasShownBackgroundSinceLastClear;
	id _fadeOutCompletionBlock;
	BOOL _fadingOut;
}
@property(readonly, assign, nonatomic, getter=isFadingOut) BOOL fadingOut;
+(id)sharedInstance;
-(void)cancelButtonPressed;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)_searchFieldReturnPressed;
-(void)_searchFieldEditingChanged;
-(void)searchGesture:(id)gesture completedShowing:(BOOL)showing;
-(void)searchGesture:(id)gesture changedPercentComplete:(float)complete;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(BOOL)tableView:(id)view wantsHeaderForSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didUnhighlightRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didHighlightRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)searchAgentClearedResults:(id)results;
-(void)searchAgentUpdatedResults:(id)results;
-(void)_resizeTableViewForPreferredContentSizeChange:(id)preferredContentSizeChange;
-(void)_keyboardWillChangeFrame:(id)_keyboard;
-(void)_handlePanRecognizer:(id)recognizer;
-(void)_handleTapRecognizer:(id)recognizer;
-(void)_handleDismissGesture;
-(void)_fadeOutAndHideKeyboardIfNecessary:(id)necessary;
-(void)_fadeForLaunchWithDuration:(double)duration completion:(id)completion;
-(void)_deselectTableViewCell;
-(void)_updateTableContents;
-(void)_startDownloadingAppForStoreIdentifier:(unsigned long long)storeIdentifier bundleIdentifier:(id)identifier;
-(void)_populateCell:(id)cell atIndexPath:(id)indexPath inTableView:(id)tableView;
-(BOOL)_shouldDisplayImagesForDomain:(unsigned)domain;
-(id)_auxiliaryTitleForABRecordID:(int)abrecordID;
-(id)_placeHolderImageForDomain:(unsigned)domain;
-(BOOL)_hasNoResultsForQuery;
-(BOOL)_hasResults;
-(BOOL)_showingKeyboard;
-(void)_setShowingKeyboard:(BOOL)keyboard;
-(void)dismiss;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

