/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBSoundPreferences : XXUnknownSuperclass {
}
+(BOOL)shouldVibrateForCurrentRingerStateWithAudioCategory:(id)audioCategory;
+(BOOL)shouldVibrateForCurrentRingerState;
+(BOOL)vibrateWhenSilent;
+(BOOL)vibrateWhenRinging;
+(id)vibratePattern;
+(BOOL)playLockSound;
+(id)ringtonePath;
+(id)ringtoneIdentifier;
+(id)calendarAlarmPath;
+(void)userDefaultsDidChanged:(id)userDefaults;
+(void)_loadDefaultsIfNeeded;
@end

