/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIStarkHomeScreenBackgroundHostInterface.h"
#import "SBUIStarkHomeScreenBackgroundProviderInterface.h"

@class SBStarkBackgroundProvider;
@protocol SBStarkBackgroundProviderRemoteViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBStarkBackgroundProviderRemoteViewController : XXUnknownSuperclass <SBUIStarkHomeScreenBackgroundHostInterface, SBUIStarkHomeScreenBackgroundProviderInterface> {
	SBStarkBackgroundProvider* _provider;
	id<SBStarkBackgroundProviderRemoteViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBStarkBackgroundProviderRemoteViewControllerDelegate> delegate;
@property(retain, nonatomic) SBStarkBackgroundProvider* provider;
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)switchToState:(id)state withAnimationName:(id)animationName;
-(void)setViewportFrame:(CGRect)frame;
-(void)viewServiceDidTerminateWithError:(id)viewService;
-(void)dealloc;
@end

