/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBStopScrollingGestureRecognizer : XXUnknownSuperclass {
}
-(BOOL)canBePreventedByGestureRecognizer:(id)recognizer;
-(BOOL)canPreventGestureRecognizer:(id)recognizer;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
@end

