/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBBWidgetSectionInfo.h"


__attribute__((visibility("hidden")))
@interface SBTodayWidgetSectionInfo : SBBBWidgetSectionInfo {
}
-(void)populateReusableView:(id)view;
-(float)heightForReusableViewInTableView:(id)tableView;
-(Class)reusableViewClass;
-(id)representedListSection;
@end

