/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBulletinObserverViewController.h"
#import "SpringBoard-Structs.h"

@class NSArray, SBBBSectionInfo, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBTodayViewController : SBBulletinObserverViewController {
	NSMutableDictionary* _sectionIDsToOrderedBulletins;
	NSArray* _todaySnippetBulletinOrder;
	NSArray* _tomorrowSnippetBulletinOrder;
	SBBBSectionInfo* _todaySectionInfo;
	SBBBSectionInfo* _tomorrowSectionInfo;
}
-(int)bulletinViewController:(id)controller insertionAnimationForBulletin:(id)bulletin inSection:(id)section;
-(void)widget:(id)widget didUpdatePreferredSize:(CGSize)size;
-(void)commitReplacementWithBulletin:(id)bulletin ofBulletin:(id)bulletin2 inSection:(id)section;
-(void)commitRemovalOfBulletin:(id)bulletin fromSection:(id)section;
-(void)commitInsertionOfBulletin:(id)bulletin beforeBulletin:(id)bulletin2 inSection:(id)section forFeed:(unsigned)feed;
-(void)_sortBulletinsForSectionWithIdentifier:(id)identifier referencingOrder:(id)order;
-(id)_bulletinOrderStringForBulletinInfo:(id)bulletinInfo;
-(id)_tomorrowSnippetBulletinOrder;
-(id)_todaySnippetBulletinOrder;
-(void)commitReloadOfSections:(id)sections;
-(void)commitRemovalOfSection:(id)section;
-(void)commitInsertionOfSection:(id)section beforeSection:(id)section2;
-(id)todayTableHeaderView;
-(id)infoForWidgetSection:(id)widgetSection;
-(id)infoForBulletin:(id)bulletin inSection:(id)section;
-(id)infoForBulletinSection:(id)bulletinSection;
-(int)widgetIdiomForCategory:(int)category;
-(UIEdgeInsets)bulletinViewControllerContentInsetsForMode:(int)mode;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)updateTableHeader;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

