/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomUpApp.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromPhone : SBUIAnimationZoomUpApp {
}
-(void)_cleanupAnimation;
-(void)_prepareAnimation;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(id)appStatusBarTransitionInfoWithStartStyleRequest:(id)startStyleRequest startOrientation:(int)orientation;
-(void)_cleanupPhonesContextHostView;
-(void)dealloc;
@end

