/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAppStatusBarTransitionInfo, UIView;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomDownApp : SBUIMainScreenAnimationController {
	UIView* _viewToAnimate;
	SBAppStatusBarTransitionInfo* _appStatusBarTransitionInfo;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)animateFakeStatusBarWithParameters:(id)parameters;
-(void)cleanupZoom;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(double)animationDelay;
-(double)animationDuration;
-(id)appContext;
-(BOOL)prefersLayerHostSnapshot;
-(id)appStatusBarTransitionInfoWithStartEffectivelyHidden:(BOOL)startEffectivelyHidden endStyleRequest:(id)request endOrientation:(int)orientation;
-(void)dealloc;
-(id)initWithDeactivatingApp:(id)deactivatingApp;
@end

