/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomUpApp.h"
#import "SBIconZoomAnimatorDelegate.h"

@class SBIconZoomAnimator;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromHome : SBUIAnimationZoomUpApp <SBIconZoomAnimatorDelegate> {
	SBIconZoomAnimator* _zoomAnimator;
}
-(void)iconZoomAnimatorWasInvalidated:(id)invalidated;
-(void)cleanupZoom;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(void)dealloc;
@end

