/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface SBUSSDAlert : SBAlert {
	unsigned _receivedString : 1;
	unsigned _dismissOnActivate : 1;
	NSTimer* _delayedDismissTimer;
}
+(void)_newSIM:(id)sim;
+(void)_daemonRestart:(id)restart;
+(id)errorStringForCode:(id)code;
+(void)test;
+(void)registerForAlerts;
+(void)registerForSettingsAlerts;
-(void)deactivate;
-(void)activate;
-(void)_delayedDismiss;
-(void)setDismissOnActivate:(BOOL)activate;
-(BOOL)receivedString;
-(BOOL)sentResponse;
-(BOOL)allowsResponse;
-(void)USSDStringAvailable:(id)available allowsResponse:(BOOL)response;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)dealloc;
@end

