/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMapTable, NSString, NSHashTable;
@protocol SBWindowContextManagerDelegate;

__attribute__((visibility("hidden")))
@interface SBWindowContextManager : XXUnknownSuperclass {
	id<SBWindowContextManagerDelegate> _delegate;
	NSString* _identifier;
	NSHashTable* _observers;
	NSMapTable* _screenToOrderedContexts;
}
@property(copy, nonatomic) NSString* identifier;
@property(assign, nonatomic) id<SBWindowContextManagerDelegate> delegate;
-(id)description;
-(id)contextWithIdentifier:(unsigned)identifier screen:(id)screen;
-(id)contextsForScreen:(id)screen;
-(unsigned)numberOfContextsForScreen:(id)screen;
-(id)trackedScreens;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)removeContext:(id)context;
-(void)addContext:(id)context;
-(void)dealloc;
@end

