/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol SBWidgetViewControllerHostDelegate <NSObject>
@optional
-(void)widget:(id)widget didUpdatePreferredSize:(CGSize)size;
-(void)widget:(id)widget requestsLaunchOfURL:(id)url;
-(void)widget:(id)widget requestsPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context completion:(id)completion;
@end

