/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBWindowContextHostView, NSMutableDictionary, UIColor, NSString, SBWindowContextManager, UIScreen, SBOrderedRequesters;
@protocol SBWindowContextHostManagerDelegate;

__attribute__((visibility("hidden")))
@interface SBWindowContextHostManager : XXUnknownSuperclass {
	SBWindowContextManager* _contextManager;
	UIScreen* _screen;
	NSString* _identifier;
	UIColor* _defaultBackgroundColorWhileHosting;
	UIColor* _defaultBackgroundColorWhileNotHosting;
	SBWindowContextHostView* _hostView;
	BOOL _suspended;
	SBOrderedRequesters* _hostRequesters;
	NSMutableDictionary* _hostRequesterInfo;
	int _jailBehavior;
	id<SBWindowContextHostManagerDelegate> _delegate;
	struct {
		unsigned delegateOverrideRequester : 1;
		unsigned delegateShouldEnableContextHostingForRequester : 1;
	} _flags;
}
@property(readonly, assign, nonatomic) unsigned contextCount;
@property(copy, nonatomic) UIColor* defaultBackgroundColorWhileNotHosting;
@property(copy, nonatomic) UIColor* defaultBackgroundColorWhileHosting;
@property(copy, nonatomic) NSString* identifier;
@property(readonly, assign, nonatomic) UIScreen* screen;
@property(assign, nonatomic) id<SBWindowContextHostManagerDelegate> delegate;
-(void)_notePropertiesSetOnRealContextHostViewWhichIReallyNeedToChangeAndIKnowWhatImDoingISwear:(id)changeAndIKnowWhatImDoingISwear originalProperties:(id)properties forRequester:(id)requester;
-(id)_realContextHostViewWhichIReallyNeedToAccessAndIKnowWhatImDoingISwear;
-(void)_hostOnDefaultWindowForRequester:(id)requester priority:(int)priority hide:(BOOL)hide;
-(id)_overrideRequesterIfNecessary:(id)necessary;
-(void)_removeRequesterInfo:(id)info;
-(void)_applyRequesterInfo:(id)info;
-(id)_infoForRequester:(id)requester;
-(void*)createIOSurfaceForFrame:(CGRect)frame excludeContext:(unsigned)context outTransform:(CGAffineTransform*)transform;
-(void*)createIOSurfaceForFrame:(CGRect)frame outTransform:(CGAffineTransform*)transform;
-(void*)createIOSurfaceForFrame:(CGRect)frame;
-(void)setContextId:(unsigned)anId hidden:(BOOL)hidden forRequester:(id)requester;
-(void)hideHostViewOnDefaultWindowForRequester:(id)requester priority:(int)priority;
-(void)hideHostViewOnDefaultWindowForRequester:(id)requester;
-(void)unhideHostViewOnDefaultWindowForRequester:(id)requester;
-(void)orderRequesterFront:(id)front;
-(void)disableHostingForRequester:(id)requester;
-(void)resumeContextHosting;
-(void)suspendContextHosting;
-(void)enableHostingForRequester:(id)requester priority:(int)priority;
-(void)enableHostingForRequester:(id)requester orderFront:(BOOL)front;
-(id)hostViewForRequester:(id)requester enableAndOrderFront:(BOOL)front;
-(id)hostViewForRequester:(id)requester;
-(id)description;
-(void)dealloc;
-(id)initWithContextManager:(id)contextManager screen:(id)screen jailBehavior:(int)behavior;
-(id)initWithContextManager:(id)contextManager screen:(id)screen;
@end

