/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransactionDelegate.h"


@protocol SBWorkspaceTransactionGroupDelegate <SBWorkspaceTransactionDelegate>
@optional
-(void)transactionGroup:(id)group childTransactionDidFinish:(id)childTransaction success:(BOOL)success;
@end

