/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransaction.h"
#import "SBWorkspaceTransactionDelegate.h"

@class NSMutableArray, NSArray;
@protocol SBWorkspaceTransactionGroupDelegate;

__attribute__((visibility("hidden")))
@interface SBWorkspaceTransactionGroup : SBWorkspaceTransaction <SBWorkspaceTransactionDelegate> {
	NSMutableArray* _transactions;
}
@property(readonly, assign, nonatomic) NSArray* transactions;
@property(assign, nonatomic) id<SBWorkspaceTransactionGroupDelegate> delegate;
-(void)transactionDidFinish:(id)transaction success:(BOOL)success;
-(void)interruptWithReason:(int)reason;
-(BOOL)canBeInterrupted;
-(BOOL)alertDidDeactivate:(id)alert;
-(BOOL)alertWillDeactivate:(id)alert;
-(BOOL)alertDidActivate:(id)alert overAlerts:(id)alerts;
-(BOOL)alertWillActivate:(id)alert overAlerts:(id)alerts;
-(BOOL)applicationExited:(id)exited;
-(BOOL)applicationLaunchDidFail:(id)applicationLaunch;
-(BOOL)applicationActivated:(id)activated;
-(BOOL)applicationDidFinishLaunching:(id)application withInfo:(id)info;
-(BOOL)applicationDidStartLaunching:(id)application withInfo:(id)info;
-(BOOL)applicationDidBecomeReceiver:(id)application fromApplication:(id)application2;
-(BOOL)applicationWillBecomeReceiver:(id)application fromApplication:(id)application2;
-(BOOL)workspaceDidResume;
-(BOOL)workspaceWillResume;
-(BOOL)workspaceDidSuspend;
-(BOOL)workspaceWillSuspend;
-(BOOL)_shouldBeWatchdogged:(id*)watchdogged;
-(void)commit;
-(void)addMilestones:(int)milestones;
-(void)_doForAllTransactions:(id)allTransactions;
-(id)description;
-(void)addTransaction:(id)transaction;
-(void)dealloc;
-(id)initWithTransactions:(id)transactions;
-(id)init;
@end

