/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_SBIconProgressTransition.h"


__attribute__((visibility("hidden")))
@interface _SBIconProgressFractionTransition : _SBIconProgressTransition {
	float _targetFraction;
}
+(id)newTransitionToFraction:(float)fraction;
-(BOOL)isCompleteWithView:(id)view;
-(void)_updateView:(id)view forDisplayedFraction:(float)displayedFraction;
-(void)completeTransitionAndUpdateView:(id)view;
-(void)updateView:(id)view withElapsedTime:(double)elapsedTime;
-(void)updateToFraction:(float)fraction;
@end

