/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol _SBIconWallpaperColorClient <NSObject>
-(BOOL)isBlurring;
-(void)setBlurring:(BOOL)blurring;
-(void)setWallpaperColor:(CGColorRef)color phase:(CGSize)phase;
-(BOOL)wantsBlur:(id)blur;
-(CGRect)wallpaperRelativeBounds;
@end

