/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BBSectionIdentity.h"


@protocol BBDataProvider <BBSectionIdentity>
-(id)sortDescriptors;
@optional
-(id)bulletinsFilteredBy:(unsigned)by enabledSectionIDs:(id)ids count:(unsigned)count lastCleared:(id)cleared;
-(id)bulletinsFilteredBy:(unsigned)by count:(unsigned)count lastCleared:(id)cleared;
-(BOOL)syncsBulletinDismissal;
-(void)handleBulletinActionResponse:(id)response;
-(void)receiveMessageWithName:(id)name userInfo:(id)info;
-(void)noteSectionInfoDidChange:(id)noteSectionInfo;
-(BOOL)migrateSectionInfo:(id)info oldSectionInfo:(id)info2;
-(id)displayNameForSubsectionID:(id)subsectionID;
-(id)defaultSubsectionInfos;
-(void)dataProviderDidLoad;
-(float)attachmentAspectRatioForRecordID:(id)recordID;
-(id)attachmentPNGDataForRecordID:(id)recordID sizeConstraints:(id)constraints;
-(id)sectionParameters;
-(id)clearedInfoForBulletins:(id)bulletins;
-(id)clearedInfoForBulletins:(id)bulletins lastClearedInfo:(id)info;
-(id)clearedInfoAndBulletinsForClearingAllBulletinsWithLimit:(unsigned)limit lastClearedInfo:(id)info;
-(id)bulletinsWithRequestParameters:(id)requestParameters lastCleared:(id)cleared;
@end

