/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBPushStoreObserver.h"
#import "BBRemoteDataProvider.h"

@class BBSectionInfo, NSObject, NSMutableSet, NSString, BBDataProviderProxy;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface RLNDataProvider : XXUnknownSuperclass <SBPushStoreObserver, BBRemoteDataProvider> {
	NSString* _sectionID;
	NSMutableSet* _publisherBulletinIDs;
	BBSectionInfo* _defaultSectionInfo;
	NSString* _displayName;
	unsigned _pushSettings;
	BBDataProviderProxy* _proxy;
	NSObject<OS_dispatch_queue>* _queue;
}
@property(retain, nonatomic) BBDataProviderProxy* proxy;
-(void)pushStoreUserDeclinedDelivery;
-(void)pushStoreUserAcceptedDelivery;
-(void)_saveUpdatedSectionInfo;
-(void)pushStoreUpdatedPushSettings;
-(void)pushStoreClearedNotifications;
-(void)pushStoreNotificationsDidChange;
-(BOOL)syncsBulletinDismissal;
-(void)noteSectionInfoDidChange:(id)noteSectionInfo;
-(id)sectionIdentifier;
-(id)sortDescriptors;
-(id)clearedInfoForBulletins:(id)bulletins lastClearedInfo:(id)info;
-(id)clearedInfoAndBulletinsForClearingAllBulletinsWithLimit:(unsigned)limit lastClearedInfo:(id)info;
-(id)bulletinsFilteredBy:(unsigned)by count:(unsigned)count lastCleared:(id)cleared;
-(id)_allBulletinsWithLimit:(unsigned)limit;
-(void)_cleanupMigrationFromBrightonWithLastClearedDate:(id)lastClearedDate;
-(id)_latestBulletinInSet:(id)set;
-(id)_bulletinForNotification:(id)notification;
-(id)_publisherBulletinIDForNotification:(id)notification;
-(id)sectionDisplayName;
-(id)defaultSectionInfo;
-(void)rebuildDefaultSectionInfoForPushSettings:(unsigned)pushSettings;
-(id)sectionParameters;
-(id)_sortKey;
-(BOOL)_isPushDataProvider;
-(void)invalidate;
-(void)dealloc;
-(id)initWithSectionID:(id)sectionID displayName:(id)name queue:(id)queue;
@end

