/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBNewsstandItemIconImageView.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherNewsstandItemIconImageView : SBNewsstandItemIconImageView {
}
+(int)_defaultIconFormat;
@end

