/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol SBAppSliderScrollingViewDelegate <NSObject>
-(void)sliderScrollerDidEndScrolling:(id)sliderScroller;
-(BOOL)sliderScroller:(id)scroller itemWantsToBeKeptInViewHierarchy:(unsigned)viewHierarchy;
-(void)sliderScroller:(id)scroller itemWantsToBeRemoved:(unsigned)beRemoved;
-(void)sliderScrollerBeganPanning:(id)panning;
-(void)sliderScroller:(id)scroller itemTapped:(unsigned)tapped;
-(void)sliderScroller:(id)scroller contentOffsetChanged:(float)changed;
-(float)sliderScrollerDistanceBetweenItemCenters:(id)centers forOrientation:(int)orientation;
-(CGSize)sliderScrollerItemSize:(id)size forOrientation:(int)orientation;
-(BOOL)sliderScroller:(id)scroller isIndexRemovable:(unsigned)removable;
-(id)sliderScroller:(id)scroller viewForIndex:(unsigned)index;
-(unsigned)sliderScrollerItemCount:(id)count;
@end

