/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBAppSliderControllerDelegate
-(void)appSwitcherNeedsToReload:(id)reload;
-(void)appSwitcherWantsToDismissImmediately:(id)dismissImmediately;
-(void)appSwitcher:(id)switcher wantsToActivateApplication:(id)activateApplication;
@end

