/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;
@protocol SBAppSwitcherPageContentView;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherPageView : XXUnknownSuperclass {
	UIView* _shadowView;
	UIView* _hitTestBlocker;
	UIView<SBAppSwitcherPageContentView>* _view;
	UIView* _overlayView;
	int _orientation;
}
@property(assign, nonatomic) float shadowAlpha;
@property(assign, nonatomic) int orientation;
@property(retain, nonatomic) UIView* overlay;
@property(retain, nonatomic) UIView<SBAppSwitcherPageContentView>* view;
+(float)_edgeBorderForOrientation:(int)orientation;
+(CGSize)sizeForOrientation:(int)orientation;
+(float)scale;
-(void)invalidate;
-(void)setShadowEnabled:(BOOL)enabled;
-(CGRect)_viewFrame;
-(CGAffineTransform)_transformForScale;
-(CGAffineTransform)_transformForOrientation:(int)orientation;
-(void)setView:(id)view animated:(BOOL)animated;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(id)description;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

