/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIPluginHost.h"

@class NSString, SBAssistantWindow, SBOperationQueue, UIViewController, NSHashTable, SBPasscodeLockDisableAssertion, NSMutableSet;
@protocol SBUIPluginViewControllerInterface;

__attribute__((visibility("hidden")))
@interface SBAssistantController : SBUIPluginHost {
	SBOperationQueue* _operationQueue;
	NSString* _appDisplayIDBeingHosted;
	SBAssistantWindow* _assistantWindow;
	BOOL _unlockedDevice;
	BOOL _launchedInStark;
	BOOL _isHidingOtherWindows;
	int _activationEvent;
	SBPasscodeLockDisableAssertion* _disableAssertion;
	NSMutableSet* _dismissingReasons;
	int _pendingDismissViewType;
	NSHashTable* _observers;
	UIViewController<SBUIPluginViewControllerInterface>* _mainScreenViewController;
}
@property(assign, nonatomic) BOOL unlockedDevice;
+(BOOL)isAssistantRunningHidden;
+(BOOL)isAssistantViewVisible:(int)visible;
+(BOOL)isAssistantVisible;
+(BOOL)shouldEnterAssistant;
+(BOOL)supportedAndEnabled;
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
-(void)uiPlugin:(id)plugin forceUpdateToInterfaceOrientation:(int)interfaceOrientation animated:(BOOL)animated;
-(void)uiPlugin:(id)plugin isNowRunning:(BOOL)running;
-(void)uiPluginUserEventOccurred:(id)occurred;
-(BOOL)uiPlugin:(id)plugin openURL:(id)url;
-(BOOL)uiPlugin:(id)plugin launchApplicationWithBundleID:(id)bundleID openURL:(id)url;
-(BOOL)uiPluginAttemptDeviceUnlock:(id)unlock withPassword:(id)password lockViewOwner:(id)owner;
-(BOOL)uiPluginWantsActivation:(id)activation forEvent:(int)event completion:(id)completion;
-(void)_dismissUIPlugin:(id)plugin animated:(BOOL)animated;
-(void)dismissPluginForEvent:(int)event;
-(BOOL)pluginSuppressesNotifications;
-(BOOL)pluginWantsScreenDimInterval:(double*)interval;
-(BOOL)pluginWantsInterfaceOrientation:(int*)orientation;
-(void)preparePluginForActivationEvent:(int)activationEvent afterInterval:(double)interval;
-(BOOL)pluginWantsActivationEvent:(int)event interval:(double*)interval;
-(void)_viewController:(id)controller animateDisappearanceWithContext:(id)context;
-(void)_viewController:(id)controller willAnimateDisappearanceWithContext:(id)context;
-(void)_viewController:(id)controller animateAppearanceWithContext:(id)context;
-(void)_viewController:(id)controller willAnimateAppearanceWithContext:(id)context;
-(void)_viewController:(id)controller setShowsStatusBar:(BOOL)bar;
-(void)_dismissForMainScreenAnimated:(BOOL)mainScreenAnimated duration:(double)duration completion:(id)completion;
-(id)_fakeStatusBarForOrientation:(int)orientation;
-(void)_presentForMainScreenAnimated:(BOOL)mainScreenAnimated completion:(id)completion;
-(void)_notifyObserversViewDidDisappear:(int)_notifyObserversView;
-(void)_notifyObserversViewWillDisappear:(int)_notifyObserversView;
-(void)_notifyObserversViewDidAppear:(int)_notifyObserversView;
-(void)_notifyObserversViewWillAppear:(int)_notifyObserversView;
-(void)_bioAuthenticated:(id)authenticated;
-(void)_starkSiriDidDisappear:(id)_starkSiri;
-(void)_starkSiriWillDisappear:(id)_starkSiri;
-(void)_starkSiriDidAppear:(id)_starkSiri;
-(void)_starkSiriWillAppear:(id)_starkSiri;
-(void)_viewDidDisappearOnMainScreen;
-(void)_viewWillDisappearOnMainScreen;
-(void)_viewDidAppearOnMainScreen;
-(void)_viewWillAppearOnMainScreen;
-(void)_cleanupContextHosting;
-(id)_activationFlags;
-(BOOL)_isPluginLoaded;
-(void)_loadPlugin;
-(BOOL)_isDismissingAllViews;
-(double)_defaultAnimatedDismissDurationForMainScreen;
-(id)transferOwnershipOfPasscodeLockDisableAssertion;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(id)mainScreenView;
-(BOOL)activateIgnoringTouches;
-(BOOL)shouldShowLockStatusBarTime;
-(void)dismissAssistantForAlertActivation:(id)alertActivation;
-(void)dismissAssistantViewIfNecessaryWithFade:(int)fade ofDuration:(double)duration completion:(id)completion;
-(void)dismissAssistantViewIfNecessaryWithFade:(int)fade ofDuration:(double)duration;
-(void)dismissAssistantViewIfNecessaryWithFade:(int)fade;
-(void)dismissAssistantViewIfNecessary:(int)necessary;
-(void)addActivationFlagsToDisplay:(id)display;
-(void)_notePluginVisibilityDidChange;
-(void)dealloc;
-(id)init;
-(BOOL)_runActivateAssistantTest:(id)test;
-(void)_activateSiriForPPT;
-(BOOL)isAssistantViewVisible:(int)visible;
@end

