/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBBBSectionInfo, SBBBBulletinInfo;

__attribute__((visibility("hidden")))
@interface SBBBInfoOperand : XXUnknownSuperclass {
	SBBBSectionInfo* _section;
	SBBBBulletinInfo* _bulletin;
}
@property(readonly, assign, nonatomic, getter=isSectionOperand) BOOL sectionOperand;
@property(readonly, assign, nonatomic) SBBBBulletinInfo* bulletin;
@property(readonly, assign, nonatomic) SBBBSectionInfo* section;
+(id)operandWithSection:(id)section bulletin:(id)bulletin;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithSection:(id)section bulletin:(id)bulletin;
@end

