/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBBBInfoOperand;

__attribute__((visibility("hidden")))
@interface SBBBCompoundInfoOperand : XXUnknownSuperclass {
	SBBBInfoOperand* _activeOperand;
	SBBBInfoOperand* _referenceOperand;
}
@property(readonly, assign, nonatomic, getter=isSectionOperand) BOOL sectionOperand;
@property(readonly, assign, nonatomic) SBBBInfoOperand* referenceOperand;
@property(readonly, assign, nonatomic) SBBBInfoOperand* activeOperand;
+(id)compoundOperandWithOperand:(id)operand referenceOperand:(id)operand2;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithOperand:(id)operand operand:(id)operand2;
@end

