/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBBItemInfo.h"

@class NSString, BBBulletin;

__attribute__((visibility("hidden")))
@interface SBBBBulletinInfo : SBBBItemInfo {
}
@property(readonly, assign, nonatomic) BBBulletin* representedBulletin;
@property(readonly, assign, nonatomic) NSString* originalSectionIdentifier;
-(id)identifier;
@end

