/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBulletinAttachmentFactory : XXUnknownSuperclass {
}
+(id)bannerTextForAdditionalAttachments:(unsigned)additionalAttachments showingImage:(BOOL)image;
+(id)listTextForAdditionalAttachmentCount:(unsigned)additionalAttachmentCount;
+(id)_nAttachments:(unsigned)attachments;
+(id)_nMoreAttachments:(unsigned)attachments;
+(id)modalImageForAttachmentType:(int)attachmentType thumbnailData:(id)data;
+(id)bannerImageForAttachmentType:(int)attachmentType thumbnailData:(id)data;
+(id)lockScreenFloatingImageForAttachmentType:(int)attachmentType thumbnailData:(id)data;
+(id)listImageForAttachmentType:(int)attachmentType thumbnailData:(id)data;
+(id)_listImageForAttachmentType:(int)attachmentType thumbnailData:(id)data forFloatingAlert:(BOOL)floatingAlert;
+(id)_imageFromPNGData:(id)pngdata;
+(id)_imageByCroppingOrPaddingImage:(id)image toSize:(CGSize)size;
+(id)_genericImageForAttachmentType:(int)attachmentType;
+(id)modalThumbnailConstraintsForAttachmentType:(int)attachmentType;
+(id)bannerThumbnailConstraintsForAttachmentType:(int)attachmentType;
+(id)lockScreenFloatingThumbnailContraintsForAttachmentType:(int)attachmentType;
+(id)listThumbnailConstraintsForAttachmentType:(int)attachmentType;
+(CGSize)bannerImageSizeForAttachmentType:(int)attachmentType thumbnailWidth:(float)width height:(float)height;
+(CGSize)listImageSizeForAttachmentType:(int)attachmentType thumbnailWidth:(float)width height:(float)height;
@end

