/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDefaultBannerViewSource.h"

@class NSArray, BBObserver, SBUISound, BBBulletin, UIImage;

__attribute__((visibility("hidden")))
@interface SBBulletinBannerItem : XXUnknownSuperclass <SBDefaultBannerViewSource> {
	BBBulletin* _seedBulletin;
	BBObserver* _observer;
	NSArray* _additionalBulletins;
	UIImage* _iconImage;
	SBUISound* _sound;
}
+(id)itemWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
+(id)itemWithBulletin:(id)bulletin andObserver:(id)observer;
-(BOOL)overridesQuietMode;
-(BOOL)isCritical;
-(BOOL)inertWhenLocked;
-(BOOL)isVIP;
-(id)attachmentImage;
-(id)attachmentText;
-(id)iconImage;
-(id)sourceDate;
-(id)message;
-(id)title;
-(id)pullDownNotification;
-(BOOL)canShowInAssistant;
-(id)sortDate;
-(id)seedBulletin;
-(id)action;
-(id)sound;
-(void)_setSound;
-(unsigned)accessoryStyle;
-(id)_appName;
-(id)additionalBulletins;
-(void)dealloc;
-(id)_initWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
@end

