/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWindow.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBBulletinWindow : SBWindow {
}
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(BOOL)_canBecomeKeyWindow;
@end

