/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIControlCenterButtonDelegate.h"
#import "SBControlCenterSectionViewController.h"
#import "SpringBoard-Structs.h"

@class NSMutableArray, AVFlashlight, SBControlCenterButton, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBCCQuickLaunchSectionController : SBControlCenterSectionViewController <SBUIControlCenterButtonDelegate> {
	SBControlCenterButton* _torchButton;
	SBControlCenterButton* _clockButton;
	SBControlCenterButton* _calculatorButton;
	SBControlCenterButton* _cameraButton;
	NSMutableArray* _buttons;
	AVFlashlight* _flashlight;
	BOOL _ccVisible;
	NSObject<OS_dispatch_queue>* _flashlightQueue;
	BOOL _flashlightOn;
}
@property(assign, nonatomic, getter=isFlashlightOn) BOOL flashlightOn;
+(Class)viewClass;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)_featureLockStateDidChangeNotification:(id)_featureLockState;
-(void)_deviceBlockStateDidChangeNotification:(id)_deviceBlockState;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)_updateTorchButtonState;
-(void)_enableTorch:(BOOL)torch;
-(void)buttonTapped:(id)tapped;
-(void)_activateAppWithBundleId:(id)bundleId url:(id)url;
-(id)_urlForButton:(id)button;
-(id)_bundleIDForButton:(id)button;
-(void)viewWillAppear:(BOOL)view;
-(void)_updateFlashlightPowerState;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)noteSettingsDidUpdate:(id)noteSettings;
-(id)view;
-(CGSize)contentSizeForOrientation:(int)orientation;
-(id)sectionIdentifier;
-(void)dealloc;
-(id)init;
@end

