/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCenterZoomSettings.h"

@class SBFAnimationSettings;

__attribute__((visibility("hidden")))
@interface SBCenterAppZoomSettings : SBCenterZoomSettings {
	SBFAnimationSettings* _appZoomSettings;
	SBFAnimationSettings* _appFadeSettings;
	double _appHeadStart;
}
@property(retain) SBFAnimationSettings* appFadeSettings;
@property(retain) SBFAnimationSettings* appZoomSettings;
@property(assign) double appHeadStart;
+(id)settingsControllerModule;
@end

