/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBControlCenterKnockoutView.h"


__attribute__((visibility("hidden")))
@interface SBControlCenterSeparatorView : SBControlCenterKnockoutView {
}
+(float)defaultBreadthForOrientation:(int)orientation;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

