/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface SBControlCenterButton : XXUnknownSuperclass {
	NSString* _identifier;
	NSNumber* _sortKey;
}
@property(copy, nonatomic) NSNumber* sortKey;
@property(copy, nonatomic) NSString* identifier;
-(void)dealloc;
@end

