/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIControlCenterControl.h"


__attribute__((visibility("hidden")))
@interface SBControlCenterKnockoutView : XXUnknownSuperclass <SBUIControlCenterControl> {
}
-(void)controlConfigurationDidChangeForState:(int)controlConfiguration;
-(void)controlAppearanceDidChangeForState:(int)controlAppearance;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

