/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBControlCenterSectionViewControllerDelegate <NSObject>
-(void)sectionWantsControlCenterDismissal:(id)dismissal;
-(void)section:(id)section updateStatusText:(id)text reason:(id)reason;
-(void)noteSectionEnabledStateDidChange:(id)noteSectionEnabledState;
@end

