/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBConferenceManager : XXUnknownSuperclass {
	BOOL _hasFaceTimeCapability;
	MGNotificationTokenStructRef _faceTimeCapabilityUpdateToken;
}
+(void)initialize;
+(id)sharedInstance;
-(void)_faceTimeAppActivationStateChanged:(id)changed;
-(void)_updateStatusBar;
-(void)updateStatusBar;
-(void)_faceTimeCapabilityChanged:(id)changed;
-(id)currentCallStatusDisplayString;
-(id)currentCallRemoteUserId;
-(void)endFaceTime;
-(void)_faceTimeStateChanged:(id)changed;
-(void)invitedToIMAVChat:(id)imavchat;
-(void)dealloc;
-(BOOL)canStartFaceTime;
-(BOOL)inFaceTime;
-(BOOL)activeFaceTimeCallExists;
-(BOOL)faceTimeInvitationExists;
-(BOOL)faceTimeIsAvailable;
-(BOOL)hasFaceTimeCapability;
-(id)_faceTimeApp;
-(id)init;
@end

