/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBScaleIconZoomAnimator.h"

@class SBCrossfadeZoomSettings, UIView;

__attribute__((visibility("hidden")))
@interface SBCrossfadeIconZoomAnimator : SBScaleIconZoomAnimator {
	UIView* _crossfadeView;
	BOOL _performsTrueCrossfade;
	BOOL _masksCorners;
}
@property(assign, nonatomic) BOOL masksCorners;
@property(assign, nonatomic) BOOL performsTrueCrossfade;
@property(retain, nonatomic) SBCrossfadeZoomSettings* zoomSettings;
-(CGPoint)_zoomedIconCenter;
-(CGRect)_zoomedFrame;
-(void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupZoom;
-(void)_setZoomFraction:(float)fraction;
-(void)_prepareZoom;
-(void)_delayedForRotation;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController crossfadeView:(id)view icon:(id)icon;
-(void)_assertCrossfadeViewSizeIfNecessary;
@end

