/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDataPlanAccountAlertItem.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDataPlanFailureAlertItem : SBDataPlanAccountAlertItem {
	NSString* _carrierName;
	BOOL _newAccount;
}
@property(assign, nonatomic, getter=isNewAccount) BOOL newAccount;
@property(copy, nonatomic) NSString* carrierName;
+(id)nowButtonTitle;
+(id)laterButtonTitle;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)dealloc;
-(id)initWithAccountURL:(id)accountURL carrierName:(id)name newAccount:(BOOL)account;
@end

