/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDisableAppStatusBarAlphaChangesAssertion : XXUnknownSuperclass {
	NSString* _reason;
}
@property(readonly, assign, nonatomic) NSString* reason;
+(id)assertionWithReason:(id)reason;
-(id)description;
-(void)dealloc;
-(id)initWithReason:(id)reason;
@end

