/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBScaleIconZoomAnimator.h"

@class _SBInnerFolderIconZoomAnimator, SBFolderIconView, SBFolderIcon, SBFloatyFolderView, SBFolderController, SBFolderZoomSettings;

__attribute__((visibility("hidden")))
@interface SBFolderIconZoomAnimator : SBScaleIconZoomAnimator {
	SBFolderController* _innerFolderController;
	SBFloatyFolderView* _innerFolderView;
	_SBInnerFolderIconZoomAnimator* _innerZoomAnimator;
}
@property(readonly, assign, nonatomic) SBFolderIconView* targetIconView;
@property(readonly, assign, nonatomic) SBFolderIcon* targetIcon;
@property(retain, nonatomic) SBFolderZoomSettings* zoomSettings;
-(CGRect)_zoomedFrame;
-(void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupZoom;
-(void)_setZoomFraction:(float)fraction;
-(void)_prepareZoom;
-(void)dealloc;
-(id)initWithOuterController:(id)outerController innerController:(id)controller folderIcon:(id)icon;
@end

