/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBGestureRecognizer : XXUnknownSuperclass {
	unsigned m_types;
	int m_state;
	id m_handler;
	unsigned m_activeTouchesCount;
	XXStruct_XgRpiA m_activeTouches[30];
	unsigned m_strikes;
	unsigned m_templateMatches;
	NSMutableArray* m_touchTemplates;
	BOOL m_includedInGestureRecognitionIsPossibleTest;
	BOOL m_sendsTouchesCancelledToApplication;
	id m_canBeginCondition;
	CGPoint m_maximumAllowedExclusiveMovement;
}
@property(assign, nonatomic) CGPoint maximumAllowedExclusiveMovement;
@property(copy, nonatomic) id canBeginCondition;
@property(assign, nonatomic) BOOL sendsTouchesCancelledToApplication;
@property(assign, nonatomic) BOOL includedInGestureRecognitionIsPossibleTest;
@property(copy, nonatomic) id handler;
@property(assign, nonatomic) int state;
@property(assign, nonatomic) unsigned types;
-(id)description;
-(void)_appendDescription:(id)description forTypes:(unsigned)types;
-(void)touchesCancelled:(SBGestureContextRef)cancelled;
-(void)touchesEnded:(SBGestureContextRef)ended;
-(void)touchesMoved:(SBGestureContextRef)moved;
-(void)touchesBegan:(SBGestureContextRef)began;
-(int)templateMatch;
-(void)addTouchTemplate:(id)aTemplate;
-(void)reset;
-(BOOL)shouldReportRecognitionPossibleToAppsForTotalMotion:(CGPoint)totalMotion;
-(BOOL)shouldReceiveTouches;
-(BOOL)isRecognized;
-(void)dealloc;
-(id)init;
@end

