/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CPLRUDictionary;

__attribute__((visibility("hidden")))
@interface SBGestureViewVendor : XXUnknownSuperclass {
	CPLRUDictionary* m_cache;
}
+(id)sharedInstance;
-(void)maskViewIfNeeded:(id)needed gestureType:(unsigned)type viewType:(int)type3 contextHostViewRequester:(id)requester app:(id)app;
-(void)dealloc;
-(id)init;
-(void)clearCacheForReason:(id)reason;
-(void)clearCacheForApp:(id)app reason:(id)reason;
-(id)viewForApp:(id)app gestureType:(unsigned)type includeStatusBar:(BOOL)bar decodeImage:(BOOL)image;
-(id)viewForApp:(id)app gestureType:(unsigned)type includeStatusBar:(BOOL)bar;
@end

