/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "_SBIconWallpaperColorClient.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol SBIconBlurryBackgroundViewObserver;

__attribute__((visibility("hidden")))
@interface SBIconBlurryBackgroundView : XXUnknownSuperclass <_SBIconWallpaperColorClient> {
	CGRect _wallpaperRelativeBounds;
	BOOL _isBlurring;
	id<SBIconBlurryBackgroundViewObserver> _observer;
	id _wantsBlurEvaluator;
	CGPoint _wallpaperRelativeCenter;
}
@property(copy, nonatomic) id wantsBlurEvaluator;
@property(readonly, assign, nonatomic) BOOL isBlurring;
@property(assign, nonatomic) CGPoint wallpaperRelativeCenter;
@property(assign, nonatomic) id<SBIconBlurryBackgroundViewObserver> observer;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)setBlurring:(BOOL)blurring;
-(void)setWallpaperColor:(CGColorRef)color phase:(CGSize)phase;
-(BOOL)wantsBlur:(id)blur;
-(CGRect)wallpaperRelativeBounds;
-(void)didAddSubview:(id)subview;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

