/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconIndexNodeObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBIconListView, SBIconZoomSettings, NSMapTable, SBIconListModel, NSMutableArray, UIWindow, NSSet, NSString, SBFolderController, UIView;
@protocol SBIconZoomAnimatorDelegate;

__attribute__((visibility("hidden")))
@interface SBIconZoomAnimator : XXUnknownSuperclass <SBIconIndexNodeObserver> {
	id<SBIconZoomAnimatorDelegate> _delegate;
	NSMapTable* _listIconToViewMap;
	NSMapTable* _dockIconToViewMap;
	float _zoomFraction;
	NSSet* _criticalIconNodeIdentifiers;
	BOOL _invalidatedForIconModifications;
	BOOL _startedAnimation;
	BOOL _startAnimationAfterRotationEnds;
	BOOL _windowIsRotating;
	NSMutableArray* _pendedAnimateZoomContexts;
	UIWindow* _animationWindow;
	SBIconListModel* _iconListModel;
	NSString* _instanceIdentifier;
	SBIconZoomSettings* _zoomSettings;
	SBFolderController* _folderController;
	SBIconListView* _iconListView;
	SBIconListView* _dockListView;
}
@property(retain, nonatomic) NSSet* criticalIconNodeIdentifiers;
@property(readonly, assign, nonatomic) UIView* referenceView;
@property(readonly, assign, nonatomic) SBIconListView* dockListView;
@property(readonly, assign, nonatomic) SBIconListView* iconListView;
@property(readonly, assign, nonatomic) SBFolderController* folderController;
@property(readonly, assign, nonatomic) BOOL invalidated;
@property(assign, nonatomic) id<SBIconZoomAnimatorDelegate> delegate;
@property(retain, nonatomic) SBIconZoomSettings* zoomSettings;
-(void)_invalidateAnimationForSignificantIconModelChangesForReason:(id)reason;
-(void)_iconModelDidReload;
-(void)_iconModelDidRelayout;
-(void)_windowFinishedRotating;
-(void)_invalidateCompletions;
-(void)_clearObservers;
-(void)_setDockListView:(id)view;
-(void)_setIconListView:(id)view;
-(void)node:(id)node didRemoveContainedNodeIdentifiers:(id)identifiers;
-(void)node:(id)node didAddContainedNodeIdentifiers:(id)identifiers;
-(id)_centralAnimationFactory;
-(void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupZoom;
-(void)_setZoomFraction:(float)fraction;
-(void)_prepareZoom;
-(BOOL)_isDelayedForRotation;
-(void)_animateToZoomFractionFromContext:(id)context;
-(void)_animateToZoomFractionFromPendingContexts;
-(void)animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withCompletion:(id)completion;
-(void)setZoomFraction:(float)fraction;
-(void)cleanup;
-(void)_cleanup:(BOOL)cleanup;
-(void)prepare;
-(unsigned)dockIconCount;
-(unsigned)listIconCount;
-(void)enumerateIconsAndIconViewsWithHandler:(id)handler;
-(id)iconViewForIcon:(id)icon;
-(id)centralAnimationFactory;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController;
@end

