/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconProgressViewDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBIconObserver.h"

@class SBIcon, UIImageView, SBIconProgressView, UIImage;

__attribute__((visibility("hidden")))
@interface SBIconImageView : XXUnknownSuperclass <SBIconObserver, SBIconProgressViewDelegate> {
	UIImageView* _overlayView;
	SBIconProgressView* _progressView;
	BOOL _isPaused;
	UIImage* _cachedSquareContentsImage;
	BOOL _showsSquareCorners;
	SBIcon* _icon;
	float _brightness;
	float _overlayAlpha;
}
@property(assign, nonatomic) BOOL showsSquareCorners;
@property(assign, nonatomic) float overlayAlpha;
@property(assign, nonatomic) float brightness;
@property(retain, nonatomic) SBIcon* icon;
+(id)dequeueRecycledIconImageViewOfClass:(Class)aClass;
+(void)recycleIconImageView:(id)view;
+(float)cornerRadius;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)iconImageDidUpdate:(id)iconImage;
-(CGRect)visibleBounds;
-(CGSize)sizeThatFits:(CGSize)fits;
-(id)squareDarkeningOverlayImage;
-(id)darkeningOverlayImage;
-(id)squareContentsImage;
-(id)contentsImage;
-(void)_clearCachedImages;
-(id)_generateSquareContentsImage;
-(void)_updateProgressMask;
-(void)_updateOverlayImage;
-(id)_currentOverlayImage;
-(void)updateImageAnimated:(BOOL)animated;
-(id)snapshot;
-(void)prepareForReuse;
-(void)layoutSubviews;
-(void)setPaused:(BOOL)paused;
-(void)setProgressAlpha:(float)alpha;
-(void)_clearProgressView;
-(void)progressViewCanBeRemoved:(id)removed;
-(void)setProgressState:(int)state paused:(BOOL)paused percent:(float)percent animated:(BOOL)animated;
-(void)_updateOverlayAlpha;
-(void)setIcon:(id)icon animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

