/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBIconColorSettings : XXUnknownSuperclass {
	BOOL _blurryFolderIcons;
	BOOL _blurryCloseBoxes;
	BOOL _suppressJitter;
	BOOL _closeBoxesEverywhere;
	float _maxSaturationBoost;
	float _maxSaturation;
	float _maxBrightnessBoost;
	float _maxBrightness;
	float _colorAlpha;
	float _whiteAlpha;
}
@property(assign, nonatomic) BOOL closeBoxesEverywhere;
@property(assign, nonatomic) BOOL suppressJitter;
@property(assign, nonatomic) float whiteAlpha;
@property(assign, nonatomic) float colorAlpha;
@property(assign, nonatomic) float maxBrightness;
@property(assign, nonatomic) float maxBrightnessBoost;
@property(assign, nonatomic) float maxSaturation;
@property(assign, nonatomic) float maxSaturationBoost;
@property(assign, nonatomic) BOOL blurryCloseBoxes;
@property(assign, nonatomic) BOOL blurryFolderIcons;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

