/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol SBIconAccessoryView <NSObject>
+(id)checkoutAccessoryImagesForIcon:(id)icon location:(int)location;
-(void)prepareForReuse;
-(void)setAccessoryBrightness:(float)brightness;
-(BOOL)displayingAccessory;
-(CGPoint)accessoryOriginForIconBounds:(CGRect)iconBounds;
-(void)configureForIcon:(id)icon location:(int)location highlighted:(BOOL)highlighted;
-(void)configureAnimatedForIcon:(id)icon location:(int)location highlighted:(BOOL)highlighted withPreparation:(id)preparation animation:(id)animation completion:(id)completion;
@end

