/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIcon.h"
#import "NSCopying.h"

@class NSString, NSMutableSet;
@protocol SBLeafIconDataSource;

__attribute__((visibility("hidden")))
@interface SBLeafIcon : SBIcon <NSCopying> {
	NSString* _leafIdentifier;
	NSString* _applicationBundleID;
	NSMutableSet* _dataSources;
	id<SBLeafIconDataSource> _activeDataSource;
	id<SBLeafIconDataSource> _dataSourceAtUninstallation;
}
-(id)nodeIdentifier;
-(void)launchFromLocation:(int)location;
-(BOOL)launchEnabled;
-(void)completeUninstall;
-(void)setUninstalled;
-(BOOL)allowsUninstall;
-(BOOL)isRecentlyUpdated;
-(int)accessoryTypeForLocation:(int)location;
-(id)accessoryTextForLocation:(int)location;
-(id)badgeNumberOrString;
-(BOOL)progressIsPaused;
-(float)progressPercent;
-(int)progressState;
-(BOOL)iconAppearsInNewsstand;
-(BOOL)canEllipsizeLabel;
-(id)displayName;
-(id)getGenericIconImage:(int)image;
-(id)generateIconImage:(int)image;
-(void)_noteDataSourceDidInvalidateNotification:(id)_noteDataSource;
-(void)_noteActiveDataSourceDidGenerateImageNotification:(id)_noteActiveDataSource;
-(void)_noteActiveDataSourceDidChangeNotification:(id)_noteActiveDataSource;
-(void)_noteActiveDataSourceDidGenerateIconFormat:(int)_noteActiveDataSource;
-(void)_noteActiveDataSourceDidChangeAndReloadIcon:(BOOL)_noteActiveDataSource;
-(id)activeDataSource;
-(void)removeIconDataSourcesOfClass:(Class)aClass;
-(void)removeIconDataSource:(id)source;
-(void)addIconDataSource:(id)source;
-(void)_updateActiveDataSource;
-(BOOL)matchesRepresentation:(id)representation;
-(id)representation;
-(id)applicationBundleID;
-(id)leafIdentifier;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)description;
-(void)dealloc;
-(id)initWithLeafIdentifier:(id)leafIdentifier applicationBundleID:(id)anId;
-(id)init;
@end

