/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockScreenPluginTransition.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenAnimatedPluginTransition : SBLockScreenPluginTransition {
}
-(void)_finalizeAndClearPluginAnimationContext;
-(void)beginTransition;
@end

