/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIDynamicAnimatorDelegate.h"
#import "SBResponderTouchDelegate.h"
#import "_UISettingsKeyObserver.h"

@class UIDynamicAnimator, SBBouncingItem, UIGestureRecognizer, SBBounceBehavior, NSMutableSet, SBBouncingSystem, SBBounceSettings, NSSet, UIView;

__attribute__((visibility("hidden")))
@interface SBLockScreenBounceAnimator : XXUnknownSuperclass <UIDynamicAnimatorDelegate, _UISettingsKeyObserver, SBResponderTouchDelegate> {
	NSMutableSet* _tapExcludedViews;
	BOOL _isAnimating;
	BOOL _bounceEnabled;
	UIView* _view;
	SBBouncingSystem* _system;
	UIDynamicAnimator* _animator;
	SBBouncingItem* _item;
	SBBounceBehavior* _behavior;
	UIGestureRecognizer* _tapRecognizer;
	UIGestureRecognizer* _panRecognizer;
	id _prepareBlock;
	id _translateBlock;
	id _canceledBlock;
	id _completedBlock;
	SBBounceSettings* _settings;
}
@property(readonly, assign, nonatomic) NSSet* tapExcludedViews;
@property(retain, nonatomic) SBBounceSettings* settings;
@property(copy) id completedBlock;
@property(copy) id canceledBlock;
@property(copy) id translateBlock;
@property(copy) id prepareBlock;
-(void)responder:(id)responder touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)responder:(id)responder touchesEnded:(id)ended withEvent:(id)event;
-(void)responder:(id)responder touchesBegan:(id)began withEvent:(id)event;
-(void)dynamicAnimatorDidPause:(id)dynamicAnimator;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)_updateSettings;
-(void)_createAnimator;
-(void)_removeAnimator;
-(void)_resetAnimator;
-(void)_beginAnimating;
-(void)_handlePanGesture:(id)gesture;
-(void)_handleTapGesture:(id)gesture;
-(void)_addPanRecognizer;
-(void)_removeTapRecognizer;
-(void)_addTapRecognizer;
-(void)removeTapExcludedView:(id)view;
-(void)addTapExcludedView:(id)view;
-(void)setBounceEnabled:(BOOL)enabled;
-(void)cancelAnimation;
-(BOOL)isAnimating;
-(void)dealloc;
-(id)initWithView:(id)view allowPan:(BOOL)pan;
@end

