/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBDisableAppStatusBarAlphaChangesAssertion;

__attribute__((visibility("hidden")))
@interface SBLockToAppStatusBarAnimator : XXUnknownSuperclass {
	SBDisableAppStatusBarAlphaChangesAssertion* _disableStatusBarAlphaChangeAssertion;
}
-(void)animateStatusBarFromLockToHome;
@end

