/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewController.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenResetRestoreViewController : SBLockOverlayViewController {
}
-(void)setResetRestoreText:(id)text;
-(void)loadView;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

