/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockScreenNotificationBannerItem.h"

@class SBUISound;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationBulletinBannerItem : SBLockScreenNotificationBannerItem {
	SBUISound* _sound;
}
-(id)_bulletinListItem;
-(id)unlockActionContext;
-(BOOL)isVIP;
-(id)attachmentImage;
-(id)attachmentText;
-(id)iconImage;
-(id)sourceDate;
-(id)message;
-(id)title;
-(id)sound;
-(void)dealloc;
-(id)initWithListItem:(id)listItem;
@end

