/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBLockOverlayContext, SBAwayViewPluginController;

__attribute__((visibility("hidden")))
@interface SBLockScreenPlugin : XXUnknownSuperclass {
	SBAwayViewPluginController* _controller;
	SBLockOverlayContext* _overlay;
	NSString* _bundleName;
}
@property(copy) NSString* bundleName;
@property(retain) SBLockOverlayContext* overlay;
@property(retain) SBAwayViewPluginController* controller;
-(void)dealloc;
@end

