/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, SBLockScreenView, SBDisableAppStatusBarAlphaChangesAssertion, _UIDynamicValueAnimation, SBLockScreenBounceAnimator;

__attribute__((visibility("hidden")))
@interface SBLockScreenSlideUpController : XXUnknownSuperclass {
	BOOL _isInScreenOffMode;
	UIView* _slidingStatusBarView;
	SBLockScreenView* _lockScreenView;
	SBLockScreenBounceAnimator* _bounceAnimator;
	_UIDynamicValueAnimation* _dynamicAnimation;
	SBDisableAppStatusBarAlphaChangesAssertion* _disableStatusBarAssertion;
}
@property(retain) SBDisableAppStatusBarAlphaChangesAssertion* disableStatusBarAssertion;
+(id)lockScreenViewFakeStatusBar;
-(id)bounceAnimator;
-(id)_newDynamicAnimationForGestureSucceeded:(BOOL)gestureSucceeded targetValue:(double)value withInitialVelocity:(double)initialVelocity;
-(id)_newBounceAnimatorWithGrabberView:(id)grabberView;
-(void)abortDynamicAnimationForScreenOff;
-(void)setInScreenOffMode:(BOOL)screenOffMode;
-(void)hideSlidingStatusBar;
-(void)finalizeGesture;
-(void)cleanupFromGesture;
-(void)prepareForSlideUpAnimation;
-(void)translateSlidingViewByY:(float)y;
-(void)gestureDidEnd:(BOOL)gesture;
-(void)gestureWillEndWithVelocity:(float)gesture;
-(void)setGrabberOnLockScreen:(id)screen;
-(id)grabberView;
-(void)dealloc;
-(void)setLockScreenView:(id)view;
-(id)lockScreenView;
@end

