/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIView, NSMutableDictionary, NSTimer, UITableView, CADisplayLink;
@protocol SBLockScreenNotificationViewDelegate, SBLockScreenNotificationModel;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationListView : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate> {
	UITableView* _tableView;
	UIView* _tableHeaderView;
	UIView* _tableFooterView;
	UIImageView* _topDropShadowView;
	UIImageView* _bottomDropShadowView;
	UIView* _containerView;
	id<SBLockScreenNotificationViewDelegate> _delegate;
	id<SBLockScreenNotificationModel> _model;
	CADisplayLink* _displayLink;
	float _currentTextAlpha;
	double _fadeStartTimestamp;
	NSTimer* _oldTextDisabledTimer;
	unsigned _indexOfNewItem;
	BOOL _notificationCellIsScrollingToPasscode;
	float _notificationScrollDecelerationRatio;
	NSMutableDictionary* _heightForListItemCache;
	float _totalContentHeight;
	float _startingScrollOffset;
	float _lastDistanceScrolled;
	BOOL _updateCellsToVisibleOnPluginWillDisable;
}
@property(assign, nonatomic) BOOL updateCellsToVisibleOnPluginWillDisable;
@property(assign, nonatomic) id<SBLockScreenNotificationModel> model;
@property(assign, nonatomic) id<SBLockScreenNotificationViewDelegate> delegate;
-(void)_cellTextFadeTimerFired:(id)fired;
-(void)_textDisabledTimerFired:(id)fired;
-(void)_clearTextFadeTimer;
-(void)_clearTextDisabledTimer;
-(void)_resetAllFadeTimers;
-(void)_disableExistingContent;
-(UIEdgeInsets)_contentViewInsets;
-(BOOL)_disableIdleTimer:(BOOL)timer;
-(void)_pluginWillDisable:(id)_plugin;
-(void)updateForRemovalOfItems;
-(void)updateForRemovalOfItemAtIndex:(unsigned)index removedItem:(id)item;
-(void)_postludeForUpdateForRemoval:(BOOL)removal;
-(void)updateForModificationOfItemWithOldIndex:(unsigned)oldIndex andNewIndex:(unsigned)index;
-(void)updateForAdditionOfItemAtIndex:(unsigned)index allowHighlightOnInsert:(BOOL)insert;
-(int)_rowAnimationForDelete;
-(int)_rowAnimationForInsert;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)_scrollingEndedInScrollView:(id)scrollView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)_setNonSelectedCellsToVisible:(BOOL)visible withSelectedCell:(id)selectedCell;
-(void)tableView:(id)view didEndDisplayingCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)_setContentForTableCell:(id)tableCell withItem:(id)item atIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)lockScreenDidEndScrollingOnPage:(int)lockScreen;
-(void)scrollToTopOfListAnimated:(BOOL)listAnimated;
-(void)setInScreenOffMode:(BOOL)screenOffMode;
-(void)_updateTotalContentHeight;
-(void)_updateBottomShadowVisibility;
-(id)_tableFooterView;
-(id)_tableHeaderView;
-(void)layoutSubviews;
-(void)prepareForRemoval;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

