/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBDismissOnlyAlertItem;

__attribute__((visibility("hidden")))
@interface SBLockdownManager : XXUnknownSuperclass {
	int _state;
	BOOL _settingUpActivationState;
	BOOL _isBricked;
	BOOL _isDeveloperDevice;
	BOOL _hasShownMismatchedSIM;
	SBDismissOnlyAlertItem* _activatingAlertItem;
	NSString* _unqiueDeviceIdentifier;
}
+(id)sharedInstance;
-(void)dealloc;
-(int)lockdownState;
-(BOOL)isDeveloperDevice;
-(BOOL)brickedDevice;
-(void)_setupActivationState;
-(void)_serviceAvailabilityChanged:(id)changed;
-(void)_activationFailed;
-(void)_resetActivationState;
-(void)_postAlertsIfNeeded;
-(BOOL)_shouldShowTelephonyAlerts;
-(void)_setCurrentAlertItem:(id)item;
-(BOOL)_isRegisteredToNetwork;
-(void)_setHasEverRegistered:(BOOL)registered;
-(BOOL)_hasEverRegistered;
-(id)init;
@end

