/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBLSApplicationPlaceholderLifecycleObserver
-(void)applicationPlaceholdersNetworkUsageChanged:(BOOL)changed;
-(void)applicationPlaceholdersIconUpdated:(id)updated;
-(void)applicationPlaceholdersInstalled:(id)installed;
-(void)applicationPlaceholdersCancelled:(id)cancelled;
-(void)applicationPlaceholdersModified:(id)modified;
-(void)applicationPlaceholdersAdded:(id)added;
@end

