/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBApplication, UIView;

__attribute__((visibility("hidden")))
@interface SBMiniAlertController : XXUnknownSuperclass {
	SBApplication* _displayShowingAnAlert;
	unsigned _sbMiniAlertVisible : 1;
	UIView* _hiddenAlertWindow;
}
+(id)sharedInstance;
-(BOOL)canShowAlerts;
-(BOOL)miniAlertVisible;
-(void)_setAlertVisibleNotifyState:(BOOL)state;
-(void)noteMiniAlertStateChanged;
-(void)hideApplicationMiniAlerts;
-(void)_hideMiniAlertsForApp:(id)app;
-(void)showApplicationMiniAlertsIfNeeded;
-(void)displayDidDismissMiniAlert:(id)display;
-(void)displayWillDismissMiniAlert:(id)display;
-(id)displayShowingAnAlert;
-(void)displayWillShowMiniAlert:(id)display;
-(void)_setDisplayShowingAnAlert:(id)alert;
-(void)deactivateAlertItemsForDisplay:(id)display;
-(void)dealloc;
-(id)init;
@end

