/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUserInstalledApplicationIcon.h"
#import "SpringBoard-Structs.h"

@class SBNewsstandApplication;

__attribute__((visibility("hidden")))
@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon {
	SBNewsstandApplication* _fakeApp;
}
@property(retain, nonatomic) SBNewsstandApplication* fakeApp;
-(id)getGenericIconImage:(int)image;
-(BOOL)iconAppearsInNewsstand;
-(BOOL)isNewsstandApplicationIcon;
-(int)iconFormatForLocation:(int)location;
-(void)launchFromLocation:(int)location;
-(BOOL)launchEnabled;
-(id)application;
-(BOOL)shouldWarmUp;
-(void)dealloc;
-(id)initWithApplication:(id)application;
-(Class)iconImageViewClassForLocation:(int)location;
-(Class)iconViewClassForLocation:(int)location;
@end

