/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconListModel.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandIconListModel : SBIconListModel {
}
+(Class)viewClass;
-(unsigned)firstFreeSlotIndexForType:(int)type;
-(BOOL)allowsAddingIcon:(id)icon;
@end

