/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBPasscodeLockAssertionTracker : XXUnknownSuperclass {
	void* _mkbAssertion;
	NSMutableSet* _assertions;
}
-(id)description;
-(id)mkbAssertionOptions;
-(BOOL)hasActiveAssertions;
-(void)removeAssertion:(id)assertion;
-(void)addAssertion:(id)assertion;
-(void)dealloc;
-(id)init;
@end

