/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBHUDView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBRotationLockHUDView : SBHUDView {
	BOOL _locked;
	BOOL locked;
}
@property(assign, nonatomic, getter=isLocked) BOOL locked;
-(id)init;
-(void)_updateLockedImage;
@end

