/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, SBLockScreenView, UIWindow, SBFadeAnimationSettings, SBFLockScreenDateView;

__attribute__((visibility("hidden")))
@interface SBScreenFadeAnimationController : XXUnknownSuperclass {
	UIWindow* _fadeWindow;
	UIView* _overlayView;
	SBFLockScreenDateView* _dateView;
	float _originalDateLeftEdge;
	float _originalDateBottomEdge;
	float _finalTimeAlpha;
	float _finalDateAlpha;
	float _finalStatusBarAlpha;
	SBLockScreenView* _lockScreenView;
	BOOL _preparingToAnimateFadeIn;
	BOOL _animatingForFadeIn;
	BOOL _animatingForFadeOut;
	int _animationToken;
	id _fadeInCompletionBlock;
	id _fadeOutCompletionBlock;
	BOOL _animatingDateTime;
	BOOL _animatingWallpaper;
	BOOL _animatingOverlay;
	BOOL _animatingContent;
	SBFadeAnimationSettings* _settings;
}
+(id)sharedInstance;
-(void)setLegibilitySettings:(id)settings;
-(void)setTextColor:(id)color;
-(void)hideDate;
-(void)setDateViewAlpha:(float)alpha;
-(void)_runCompletionHandlerForFadeIn:(BOOL)anIn;
-(void)_handleAnimationCompletionIfNecessaryForFadeIn:(BOOL)anIn;
-(void)fadeOutWithCompletion:(id)completion;
-(void)_startFadeAnimationsForFadeIn:(BOOL)anIn;
-(void)_cleanupAnimationWhenInterruptingFadeIn:(BOOL)anIn;
-(void)_assistantVisibilityChanged;
-(void)_mediaControlsDidShow;
-(void)_blankScreenStateChanged;
-(void)_startFadeInIfNecessary;
-(void)prepareToFadeInWithTimeAlpha:(float)timeAlpha dateAlpha:(float)alpha statusBarAlpha:(float)alpha3 lockScreenView:(id)view existingDateView:(id)view5 completion:(id)completion;
-(void)_setRelevantLockScreenViewsHidden:(BOOL)hidden;
-(void)_adjustViewsForCurrentOrientation;
-(void)updateDateFrameHorizontalOffset:(float)offset verticalOffset:(float)offset2;
-(BOOL)isFadeOutAnimationInProgress;
-(BOOL)isFadeInAnimationInProgress;
-(void)_createFadeWindowForFadeIn:(BOOL)anIn;
-(double)fadeOutAnimationDuration;
-(double)fadeInAnimationDuration;
-(void)dealloc;
-(id)init;
@end

