/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBScreenObserver <NSObject>
-(void)screenManager:(id)manager didReconnectScreen:(id)screen;
-(void)screenManager:(id)manager didDisconnectScreen:(id)screen;
-(void)screenManager:(id)manager didChangeSuppressionOfScreen:(id)screen;
@end

