/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBaseSoftwareUpdateAlertItem.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface SBSoftwareUpdateForcedInstallAlertItem : SBBaseSoftwareUpdateAlertItem {
	NSTimer* _timer;
	unsigned _timeLeftUntilInstall;
	BOOL _delayOnDismissForNonUserAction;
	BOOL _delayAfterNextUnlock;
}
@property(assign, nonatomic) BOOL delayAfterNextUnlock;
@property(assign, nonatomic) BOOL delayOnDismissForNonUserAction;
-(BOOL)dismissOnLock;
-(void)performUnlockAction;
-(BOOL)shouldShowInLockScreen;
-(id)shortLockLabel;
-(id)lockLabel;
-(BOOL)allowMenuButtonDismissal;
-(BOOL)undimsScreen;
-(void)_timerFired;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)willDeactivateForReason:(int)reason;
-(void)willPresentAlertView:(id)view;
-(void)updateBodyText;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)_installUpdate;
-(void)dealloc;
-(id)initWithDescriptor:(id)descriptor;
@end

