/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLeafIcon.h"


__attribute__((visibility("hidden")))
@interface SBStarkNowPlayingIcon : SBLeafIcon {
}
-(void)_nowPlayingInfoChanged:(id)changed;
-(id)generateIconImage:(int)image;
-(void)drawNowPlayingKnobIconInBounds:(CGRect)bounds withArtwork:(id)artwork;
-(void)drawNowPlayingCanvasIconInBounds:(CGRect)bounds withArtwork:(id)artwork;
-(void)dealloc;
-(id)initWithLeafIdentifier:(id)leafIdentifier applicationBundleID:(id)anId;
@end

