/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkWorkspaceTransaction.h"

@class SBApplication;

__attribute__((visibility("hidden")))
@interface SBStarkToAppWorkspaceTransaction : SBStarkWorkspaceTransaction {
	SBApplication* _toApp;
	BOOL _fromAssistant;
}
@property(readonly, assign, nonatomic) SBApplication* toApp;
-(void)_transactionComplete;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller to:(id)to;
@end

