/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconListModelObserver.h"
#import "SBStarkLauncher.h"
#import "SBLeafIconDataSource.h"
#import "SpringBoard-Structs.h"

@class NSMutableDictionary, NSMutableSet, SBStarkIconListModel, SBStarkFakeIconOperationController;
@protocol SBStarkAutoHideControlBarDelegate;

__attribute__((visibility("hidden")))
@interface SBStarkLauncherViewController : XXUnknownSuperclass <SBIconListModelObserver, SBStarkLauncher, SBLeafIconDataSource> {
	NSMutableSet* _displayIdentifiers;
	NSMutableDictionary* _fakeAppsByIdentifier;
	SBStarkIconListModel* _iconList;
	unsigned _batchCount;
	BOOL _needsReloadAtEndOfBatch;
	SBStarkFakeIconOperationController* _fakeIconOperationController;
	id<SBStarkAutoHideControlBarDelegate> _autoHideDelegate;
}
@property(assign, nonatomic) id<SBStarkAutoHideControlBarDelegate> autoHideDelegate;
@property(retain, nonatomic) SBStarkFakeIconOperationController* fakeIconOperationController;
@property(readonly, assign, nonatomic) BOOL obscuresControlBar;
@property(readonly, assign, nonatomic) BOOL hidesAutomatically;
@property(readonly, assign, nonatomic) SBStarkIconListModel* iconList;
@property(assign, nonatomic) float height;
+(float)desiredHeightForBounds:(CGRect)bounds;
-(BOOL)iconIsRecentlyUpdated:(id)updated;
-(BOOL)icon:(id)icon launchFromLocation:(int)location;
-(BOOL)iconAllowsLaunch:(id)launch;
-(BOOL)iconCompleteUninstall:(id)uninstall;
-(BOOL)iconAllowsUninstall:(id)uninstall;
-(id)iconFormattedAccessoryString:(id)string;
-(id)iconBadgeNumberOrString:(id)string;
-(int)iconAccessoryType:(id)type;
-(BOOL)iconProgressIsPaused:(id)paused;
-(float)iconProgressPercent:(id)percent;
-(int)iconProgressState:(id)state;
-(BOOL)iconAppearsInNewsstand:(id)newsstand;
-(BOOL)iconCanEllipsizeLabel:(id)label;
-(id)icon:(id)icon defaultImageWithFormat:(int)format;
-(id)icon:(id)icon imageWithFormat:(int)format;
-(unsigned)iconPriority:(id)priority;
-(id)iconDisplayName:(id)name;
-(void)iconList:(id)list didRemoveIcon:(id)icon;
-(void)iconList:(id)list didReplaceIcon:(id)icon withIcon:(id)icon3;
-(void)iconList:(id)list didAddIcon:(id)icon;
-(void)_noteIconModelChanged:(id)changed;
-(void)_noteIconModelActionOnIcon:(id)icon;
-(void)_noteInstalledApplicationsDidChange:(id)_noteInstalledApplications;
-(void)_decrementBatch;
-(void)_incrementBatch;
-(void)_doAsBatchedUpdate:(id)update;
-(id)_sortedListOfDisplayIDs;
-(BOOL)_isStarkAware:(id)aware;
-(void)_reloadIconList;
-(void)_removeAppForDisplayIdentifier:(id)displayIdentifier;
-(void)_addIconIfPossible:(id)possible withDisplayIdentifier:(id)displayIdentifier;
-(void)relayoutIcons;
-(id)suffixFakeIcons;
-(id)prefixFakeIcons;
-(int)iconLocation;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

