/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBVolumePressBandit.h"
#import "SBStarkBannerSource.h"
#import "BBObserverDelegate.h"
#import "SpringBoard-Structs.h"

@class NSSet, BBObserver;

__attribute__((visibility("hidden")))
@interface SBStarkBulletinBannerSource : SBStarkBannerSource <BBObserverDelegate, SBVolumePressBandit> {
	BBObserver* _bbObserver;
	NSSet* _whitelistedSectionIDs;
}
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)_reloadVolumePressBanditPreference;
-(void)observer:(id)observer noteServerReceivedResponseForBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)_showTestBanner:(id)banner;
-(BOOL)_shouldShowBulletin:(id)bulletin;
-(void)dealloc;
-(id)initWithAllowedTarget:(id)allowedTarget;
@end

