/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_UIBasicAnimationFactory.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBStarkSlideAnimationFactory : XXUnknownSuperclass <_UIBasicAnimationFactory> {
	double _startTime;
}
@property(assign, nonatomic) double startTime;
-(id)_timingFunctionForAnimation;
-(id)_basicAnimationForView:(id)view withKeyPath:(id)keyPath;
@end

