/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationControllerDelegate.h"
#import "SBStarkToAppWorkspaceTransaction.h"

@class SBUIAnimationController, SBAlert;

__attribute__((visibility("hidden")))
@interface SBStarkAlertToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerDelegate> {
	SBAlert* _alert;
	SBUIAnimationController* _animation;
	BOOL _animatedAppActivation;
	BOOL _animatingAlertSuspension;
	BOOL _deactivateAfterNextLaunch;
	BOOL _activatingLauncher;
	BOOL _fromAssistant;
}
@property(readonly, assign, nonatomic) SBAlert* alert;
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(void)_handleFailure;
-(void)_deactivateAlertIfNecessary;
-(void)_alertAnimationComplete:(id)complete;
-(void)_transactionComplete;
-(void)_endAnimation;
-(BOOL)selfStarkAlertDidDeactivate:(id)selfStarkAlert;
-(BOOL)selfStarkAlertWillDeactivate:(id)selfStarkAlert;
-(BOOL)selfApplicationExited:(id)exited;
-(BOOL)selfApplicationLaunchDidFail:(id)selfApplicationLaunch;
-(BOOL)selfApplicationDidFinishLaunching:(id)selfApplication withInfo:(id)info;
-(BOOL)selfApplicationDidBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfApplicationWillBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfApplicationActivated:(id)activated;
-(int)_setupMilestonesFrom:(id)from to:(id)to;
-(id)_newAnimationControllerFrom:(id)from to:(id)to;
-(BOOL)_hasAnimation;
-(void)_beginAnimation;
-(void)_commit;
-(id)debugDescription;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller alert:(id)alert toApplication:(id)application;
@end

