/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkWorkspaceTransaction.h"

@class SBAlert;

__attribute__((visibility("hidden")))
@interface SBStarkAlertToAlertWorkspaceTransaction : SBStarkWorkspaceTransaction {
	SBAlert* _activatingAlert;
	SBAlert* _deactivatingAlert;
	BOOL _activation;
}
-(BOOL)selfStarkAlertDidDeactivate:(id)selfStarkAlert;
-(BOOL)selfStarkAlertWillDeactivate:(id)selfStarkAlert;
-(BOOL)selfStarkAlertDidActivate:(id)selfStarkAlert overAlerts:(id)alerts;
-(BOOL)selfStarkAlertWillActivate:(id)selfStarkAlert overAlerts:(id)alerts;
-(void)_commit;
-(id)debugDescription;
-(void)dealloc;
-(id)_initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller activatingAlert:(id)alert deactivatingAlert:(id)alert5 activation:(BOOL)activation;
-(id)initDeactivationWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller from:(id)from to:(id)to;
-(id)initActivationWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller from:(id)from to:(id)to;
@end

