/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIImageView, NSArray, UIImage;

__attribute__((visibility("hidden")))
@interface SBStarkIconImageView : XXUnknownSuperclass {
	UIImageView* _imageView;
	UIImage* _image;
	float _brightness;
	unsigned _outerStripes;
	unsigned _innerStripes;
	BOOL _needsStripeUpdating;
	NSArray* _outerStripesViews;
	NSArray* _innerStripesViews;
	UIView* _brightnessView;
}
@property(assign, nonatomic) unsigned innerStripes;
@property(assign, nonatomic) unsigned outerStripes;
@property(assign, nonatomic) float brightness;
@property(retain, nonatomic) UIImage* image;
-(id)_viewsForEdges:(unsigned)edges ofWidth:(float)width inFrame:(CGRect)frame withBGColor:(id)bgcolor outRect:(CGRect*)rect;
-(void)_updateStripesIfNeeded;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

