/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, SBPasscodeLockDisableAssertion;

__attribute__((visibility("hidden")))
@interface SBSyncController : XXUnknownSuperclass {
	int _restoreState;
	int _resetState;
	int _restoreTimerState;
	NSTimer* _restoreTimer;
	NSTimer* _progressTimer;
	BOOL _showingResetUI;
	BOOL _appsChangedDuringSync;
	int _restoreStartedNotifyToken;
	int _restoreEndedNotifyToken;
	SBPasscodeLockDisableAssertion* _disableDeviceLockAssertion;
}
+(id)sharedInstance;
-(BOOL)isInUse;
-(void)_appInstallationNotification;
-(void)_setupRestoreTimer;
-(void)_restoreTimerFired:(id)fired;
-(BOOL)_isBackupAgentRunning;
-(void)_invalidateRestoreTimer;
-(void)_resetEnded:(id)ended;
-(void)_resetStarted:(id)started;
-(void)didEndResetting;
-(void)beginResetting:(BOOL)resetting;
-(void)_delayedBeginReset;
-(void)_updateProgress;
-(void)_delayedQuitApplications;
-(int)resetState;
-(BOOL)isResetting;
-(void)didEndRestoring:(int)restoring;
-(void)finishEndRestoring;
-(void)_rebootNow;
-(void)cancelRestoring;
-(void)finishedTerminatingApplications;
-(void)beginRestoring;
-(void)_killApplications;
-(void)_notifyRestoreCanProceed;
-(int)restoreState;
-(BOOL)isRestoring;
-(void)_wirelessSyncEnded:(id)ended;
-(void)syncSessionDidEnd;
-(void)_setRestoreState:(int)state;
-(void)stopObserving;
-(void)startObserving;
-(void)dealloc;
@end

