/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBBSectionInfo.h"


__attribute__((visibility("hidden")))
@interface SBTodaySectionInfo : SBBBSectionInfo {
}
-(float)heightForReusableViewInTableView:(id)tableView;
-(Class)reusableViewClass;
-(id)identifier;
@end

