/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TPSuperBottomBarDelegateProtocol.h"
#import "SBAlertView.h"
#import "SpringBoard-Structs.h"

@class UIImageView, TPSuperBottomBar, TPLCDView, UIView, UIImage;

__attribute__((visibility("hidden")))
@interface SBTTYPromptAlertDisplay : SBAlertView <TPSuperBottomBarDelegateProtocol> {
	UIView* _containerView;
	UIImageView* _backgroundView;
	UIView* _voiceAndTTYWrapperView;
	TPSuperBottomBar* _cancelBar;
	TPLCDView* _promptView;
	BOOL _didAnimateIn;
	UIImage* _calleeImage;
	BOOL _isFullscreenImage;
	BOOL _imageSetupDone;
}
-(id)thumbnailImage;
-(id)backgroundImage;
-(void)computeImageInformation;
-(id)customizedTitleForItemInBar:(id)bar withActionType:(int)actionType;
-(void)bottomBarActionPerformed:(int)performed fromBar:(id)bar;
-(void)_ignore:(id)ignore;
-(void)_chooseTTYMode:(id)mode;
-(void)_chooseVoiceMode:(id)mode;
-(void)_makeCall;
-(void)startAnimatingIn;
-(void)dismiss;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isSupportedInterfaceOrientation:(int)orientation;
-(float)_lcdYOffset;
-(void)dealloc;
@end

