/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomDownAppToHome.h"

@class SBLockToAppStatusBarAnimator, SBLockScreenViewController;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomDownLockScreenCameraToHome : SBUIAnimationZoomDownAppToHome {
	SBLockScreenViewController* _lockScreenViewController;
	SBLockToAppStatusBarAnimator* _statusBarAnimator;
}
-(void)_prepareAnimation;
-(void)animateZoomWithCompletion:(id)completion;
-(void)animateFakeStatusBarWithParameters:(id)parameters;
-(BOOL)_shouldTakeActivationAssertionForDeactivatingApp;
-(BOOL)_shouldUpdateStatusBarOnContentRestore;
-(void)dealloc;
-(id)initWithLockScreenViewController:(id)lockScreenViewController;
@end

