/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class SBUIFullscreenAlertAdapter, SBAlertManager;

__attribute__((visibility("hidden")))
@interface SBUIAnimationFadeHomeToPluginAlert : SBUIMainScreenAnimationController {
	SBAlertManager* _alertManager;
	SBUIFullscreenAlertAdapter* _alert;
	BOOL _alertIsTransparent;
	BOOL _alertViewIsAnimatingItself;
	BOOL _finishedPrimaryFadeAnimation;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_alertViewFinishedAnimatingItself;
-(void)_fadeAnimationFinished;
-(void)_evaluateTotalAnimationCompletion;
-(void)_animationFinished;
-(void)_prepareAnimation;
-(double)animationDuration;
-(void)dealloc;
-(id)initWithAlertManager:(id)alertManager alert:(id)alert;
@end

