/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBPluginManager.h"

@class NSMutableDictionary, SBUIPluginHost;

__attribute__((visibility("hidden")))
@interface SBUIPluginManager : SBPluginManager {
	NSMutableDictionary* _uiPlugins;
	SBUIPluginHost* _pendingActivation;
	SBUIPluginHost* _hostPendingActivation;
}
@property(retain) SBUIPluginHost* hostPendingActivation;
+(id)sharedInstance;
-(BOOL)overrideScreenDimInterval:(double*)interval;
-(BOOL)suppressingNotifications;
-(BOOL)overrideInterfaceOrientation:(int*)orientation;
-(BOOL)handleActivationEvent:(int)event;
-(void)cancelPendingActivationEvent:(int)event;
-(void)prepareForActivationEvent:(int)activationEvent afterInterval:(double)interval;
-(BOOL)wantsActivationEvent:(int)event interval:(double*)interval;
-(BOOL)handleMenuButtonTap;
-(BOOL)handleMenuButtonDownEvent;
-(id)loadedUIPluginHosts;
-(id)_loadedUIPluginHostsVisible:(BOOL)visible;
-(id)loadedUIPlugins;
-(BOOL)unloadUIPlugin:(id)plugin forHost:(id)host;
-(id)loadUIPluginNamed:(id)named withHost:(id)host;
@end

