/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationFadeAlertToPhone.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationSnapAlertToPhone : SBUIAnimationFadeAlertToPhone {
}
-(void)_cleanupAnimation;
-(BOOL)_shouldAnimateWallpaper;
-(void)_startAnimation;
@end

