/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"


@protocol SBUIStarkHomeScreenBackgroundProviderInterface
-(void)switchToState:(id)state withAnimationName:(id)animationName;
-(void)setViewportFrame:(CGRect)frame;
@end

