/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationController.h"

@class SBStarkScreenController;

__attribute__((visibility("hidden")))
@interface SBUIStarkScreenAnimationController : SBUIAnimationController {
	SBStarkScreenController* _starkScreenController;
}
@property(readonly, assign, nonatomic) SBStarkScreenController* starkScreenController;
-(id)_getTransitionWindow;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app starkScreenController:(id)controller;
@end

