/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBWallpaperObserver <NSObject>
@optional
-(void)wallpaperGeometryDidChangeForVariant:(int)wallpaperGeometry;
-(void)wallpaperLegibilitySettingsDidChange:(id)wallpaperLegibilitySettings forVariant:(int)variant;
-(void)wallpaperDidChangeForVariant:(int)wallpaper;
-(void)wallpaperWillChangeForVariant:(int)wallpaper;
@end

