/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBWindowContextAppearance.h"

@class UIColor, SBWindowContextHostManager;

__attribute__((visibility("hidden")))
@interface SBWindowContextHostWrapperView : XXUnknownSuperclass <SBWindowContextAppearance> {
	SBWindowContextHostManager* _manager;
	UIColor* _backgroundColorWhileNotHosting;
	UIColor* _backgroundColorWhileHosting;
}
@property(retain, nonatomic) UIColor* backgroundColorWhileNotHosting;
@property(retain, nonatomic) UIColor* backgroundColorWhileHosting;
-(id)description;
-(id)window;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)_didRemoveSubview:(id)subview;
-(void)didAddSubview:(id)subview;
-(void)clearManager;
-(void)updateBackgroundColor;
-(void)_toggleBackgroundColorIfNecessary;
-(id)_backgroundColorWhileNotHosting;
-(id)_backgroundColorWhileHosting;
-(void)_hostingStatusChanged;
-(BOOL)_isReallyHosting;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame manager:(id)manager;
@end

