/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSArray, NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBWorkStore : XXUnknownSuperclass {
	NSMutableDictionary* _workItemsPerKey;
	NSMutableArray* _keysWithWork;
	NSMutableArray* _observers;
	NSObject<OS_dispatch_queue>* _dispatchQueue;
	unsigned _maxWorkPerKey;
	NSMutableDictionary* _workExpirationPeriods;
	double _defaultWorkExpirationPeriod;
}
@property(readonly, assign, nonatomic) unsigned maxWorkPerKey;
@property(readonly, assign, nonatomic) NSMutableArray* observers;
@property(readonly, assign, nonatomic) NSMutableDictionary* workItemsPerKey;
@property(assign, nonatomic) double defaultWorkExpirationPeriod;
@property(readonly, assign, nonatomic) NSArray* keysWithWork;
-(id)description;
-(void)_notifyObserversWorkDidChange;
-(void)_queue_expireWorkForKey:(id)key;
-(void)setWorkExpirationPeriod:(double)period forKey:(id)key;
-(void)purgeWorkForKey:(id)key;
-(id)dequeueWorkForKey:(id)key;
-(void)addWorkItem:(id)item forKey:(id)key;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)dealloc;
-(id)initWithMaximumNumberOfWorkItemsPerKey:(unsigned)workItemsPerKey;
@end

